Update data streaming docs
scipp/scippneutron pull request #104
Opened 2021-06-17 15:45 UTC by matthew-d-jones

Closes #68

2021-06-21 09:02 UTC, OwenArnold requested changes
Really nice. I can't think of much more in terms of major things that this document does not explain.

2021-06-21 09:02 UTC, OwenArnold commented on docs/developer/data-stream.rst
> +
Did you consider making this a notebook and executing as part of the docs. Or is that just going to be too complex?

2021-06-24 10:29 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +process to be cleanly stopped at a request from the main, notebook, process.
It will be. I have implemented a stop button widget on a feature branch which will address #69.

2021-06-24 10:35 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +    .. code-block:: sh
It is definitely present when I build the docs.

2021-06-24 10:36 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +
Running a Kafka broker etc as part of building the docs seems like a major headache.

2021-06-24 10:36 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +to provide a convenient "serialise" and "deserialise" method for each schema
Done

2021-06-24 10:37 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +The architecture of the implementation under ``data_stream()`` is sketched in the following diagram.
Done https://github.com/scipp/scippneutron/pull/104/files#diff-5801e99b5545957b87ca1f84492810043cc8b6f914a718adc9879c170a58c52eR79

2021-06-24 10:38 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +experiment run, for example instrument geometry. These data are yielded from the generator as
I've added a paragraph on this https://github.com/scipp/scippneutron/pull/104/files#diff-5801e99b5545957b87ca1f84492810043cc8b6f914a718adc9879c170a58c52eR90-R100

2021-06-24 10:38 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +in the buffer as a single ``DataArray`` into a ``multiprocessing.Queue`` for the ``data_stream``
Done, see paragraph I linked in previous comment

2021-06-24 10:40 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
> +to create instances of ``FakeConsumer`` instead of ``KafkaConsumer``, additionally an ``mp.Queue``
I've tried to clarify here https://github.com/scipp/scippneutron/pull/104/files#diff-5801e99b5545957b87ca1f84492810043cc8b6f914a718adc9879c170a58c52eR154-R155

2021-06-24 11:06 UTC, OwenArnold commented on docs/developer/data-stream.rst
> +loop and accumulate the result, for example sum a histogram.
Great thanks!

2021-06-24 11:07 UTC, OwenArnold approved these changes

2021-06-25 07:31 UTC, merged