Avoid error when loading log in NeXus file with unrecognised units
scipp/scippneutron pull request #106
Opened 2021-06-23 16:27 UTC by matthew-d-jones

Warn the user and use `dimensionless` if units in `NXlog` are not recognised.
Problem was discovered when trying to load ISIS files with units such as "is_vetoing", "frames" and "events". I notice that "mBar" is also not recognised, should we do something about that one?

2021-06-23 18:07 UTC, OwenArnold requested changes
Aside from one minor change, looks good.

2021-06-23 18:07 UTC, OwenArnold commented on python/tests/test_load_nexus.py
> +    unknown_unit = "elephants"
:)

2021-06-23 18:07 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_log_data.py
> +        warn(f"Unrecognised unit '{unit}' for value dataset "
```suggestion
        warn(f"Unrecognized unit '{unit}' for value dataset "
```

2021-06-24 08:43 UTC, OwenArnold approved these changes

2021-06-24 08:45 UTC, OwenArnold commented
> "mBar" is also not recognised, should we do something about that one?
units library is place to fix this specific issue, thought the fix here is correct as there could be many unit types that are not understood. Is `mbar` accepted by the units library?

2021-06-24 08:45 UTC, merged

2021-06-24 08:48 UTC, matthew-d-jones commented
> > "mBar" is also not recognised, should we do something about that one?
> 
> units library is place to fix this specific issue, thought the fix here is correct as there could be many unit types that are not understood. Is `mbar` accepted by the units library?

`mbar` works fine, it is the capitalisation that causes the problem.