Add option to stop data stream at end of run or on button press
scipp/scippneutron pull request #116
Opened 2021-07-09 16:38 UTC by matthew-d-jones

Closes #69

2021-07-16 09:10 UTC, nvaytet commented on docs/developer/data-stream.rst
Trying to run this locally but cannot start the nexus streamer anymore:
```
Traceback (most recent call last):
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/bin/nexus_streamer", line 5, in <module>
    from nexus_streamer.launch_nexus_streamer import launch_streamer
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/nexus_streamer/launch_nexus_streamer.py", line 13, in <module>
    from .publish_run_message import (
  File "/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/nexus_streamer/publish_run_message.py", line 1, in <module>
    from streaming_data_types.run_start_pl72 import serialise_pl72, DetectorSpectrumMap
ImportError: cannot import name 'DetectorSpectrumMap' from 'streaming_data_types.run_start_pl72' (/home/nvaytet/software/miniconda3/envs/scipp-developer/lib/python3.7/site-packages/streaming_data_types/run_start_pl72.py)
```

2021-07-16 09:40 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
I think you need to update your `ess-streaming-data-types` dependency.

2021-07-16 09:47 UTC, nvaytet commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
When trying this locally, I cannot get it to work.
No widgets appear below the `create_task` cell and the plot does not update.
![Screenshot at 2021-07-16 11-45-16](https://user-images.githubusercontent.com/39047984/125928415-842e7e44-2f4d-4f1f-b6e5-eee0d4a9afc4.png)

I verified that the plot does update if I switch back to the `main` branch.

2021-07-16 09:53 UTC, matthew-d-jones commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
I'm not sure why the error is being swallowed, but the problem is that `start_time=StartTime.start_of_run` should now be ``start_time=StartTime.START_OF_RUN`.

2021-07-16 10:10 UTC, nvaytet commented on python/src/scippneutron/data_streaming/_data_stream_widget.py
> +        b["owner"].description = "Stopping..."
I guess one feature users might ask as soon as we show them this button is if they can also have a 'Pause' button, so that you don't stop the streaming but the plot stops updating so you can have a good long look at it, and then resume the updates when you want and it would update the plot with a large chunk of data that has arrived since you pressed 'Pause'.

But maybe that would simply be in the `my_stream_func` that updates the plot? Just `return` early if the value of the 'Pause' button is `True`

2021-07-16 10:10 UTC, nvaytet commented on python/src/scippneutron/data_streaming/data_stream.py
> +    # https://pytorch.org/docs/stable/notes/multiprocessing.html
:+1:

2021-07-16 10:10 UTC, nvaytet commented on python/tests/test_data_stream.py
> +        n_chunks += 1
Is it also possible to make a test where you simulate a button click on the Stop button by programmatically changing the value of the ToggleButton?

2021-07-16 10:11 UTC, nvaytet commented on docs/developer/data-stream.rst
see https://github.com/ess-dmsc/nexus-streamer-python/issues/26

2021-07-16 10:14 UTC, nvaytet commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
Ah, my mistake

2021-07-16 10:15 UTC, nvaytet commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
I am getting a warning in the log console on the first plot update:
```
/home/nvaytet/code/neutron/jupyter/scippneutron/data_streaming/data_stream.py:261: UnknownFlatbufferIdWarning: Received 1 messages with unrecognised FlatBuffer ids
  warn(new_data)
```

2021-07-16 10:17 UTC, nvaytet commented on python/src/scippneutron/data_streaming/_data_stream_widget.py
> +            widgets.VBox([
I would actually suggest to put this on a horizontal line, as vertical space in jupyter notebooks is a precious resource

2021-07-16 10:18 UTC, nvaytet commented on docs/developer/data-stream.rst
I had installed those conda packages this morning

2021-07-16 10:18 UTC, matthew-d-jones commented on python/src/scippneutron/data_streaming/_data_stream_widget.py
> +        b["owner"].description = "Stopping..."
Ideally you'd actually tell the consumers to pause getting data from Kafka, otherwise you could be accumulating a lot of data while it is paused.

2021-09-14 14:16 UTC, Tom-Willemsen requested changes
Probably due to changes to main since these changes were made, but several of the unit tests are failing in `convert` calls, with errors of the form:

```
FAILED tests/test_neutron.py::test_neutron_convert - TypeError: convert(): incompatible function arguments. The following argument types are supported:
```

Additionally I am getting inconsistent failures in some of the data streaming tests, of the following form. These are not consistent, it can be a different test each time, or sometimes none at all
```
____________________________________________________________________________________________________ test_data_stream_returns_metadata _____________________________________________________________________________________________________

queues = (<multiprocessing.queues.Queue object at 0x7f4d6372cd30>, <multiprocessing.queues.Queue object at 0x7f4d69552970>, <multiprocessing.queues.Queue object at 0x7f4d63f8c790>)

    @pytest.mark.asyncio
    async def test_data_stream_returns_metadata(queues):
        data_queue, worker_instruction_queue, test_message_queue = queues
        run_info_topic = "fake_topic"
        test_instrument_name = "DATA_STREAM_TEST"
    
        # The Kafka topics to get metadata from are recorded as "stream" objects in
        # the nexus_structure field of the run start message
        # There are currently 3 schemas for metadata, they have flatbuffer ids
        # f142, senv and tdct
        f142_source_name = "f142_source"
        f142_log_name = "f142_log"
        senv_source_name = "senv_source"
        senv_log_name = "senv_log"
        tdct_source_name = "tdct_source"
        tdct_log_name = "tdct_log"
        streams = [
            Stream(f"/entry/{f142_log_name}", "f142_topic", f142_source_name, "f142",
                   "double", "m"),
            Stream(f"/entry/{senv_log_name}", "senv_topic", senv_source_name, "senv",
                   "double", "m"),
            Stream(f"/entry/{tdct_log_name}", "tdct_topic", tdct_source_name, "tdct")
        ]
    
        test_stream_args = TEST_STREAM_ARGS.copy()
        test_stream_args["topics"] = None
        n_chunks = 0
        async for data in _data_stream(data_queue,
                                       worker_instruction_queue,
                                       run_info_topic=run_info_topic,
                                       query_consumer=FakeQueryConsumer(
                                           test_instrument_name, streams=streams),
                                       halt_after_n_data_chunks=2,
                                       **test_stream_args,
                                       test_message_queue=test_message_queue):
            data_from_stream = data
    
            if n_chunks == 0:
                # Fake receiving a Kafka message for each metadata schema
                # Do this after the run start message has been parsed, so that
                # a metadata buffer will have been created for each data source
                # described in the start message.
                f142_value = 26.1236
                f142_timestamp = 123456  # ns after epoch
                f142_test_message = serialise_f142(f142_value, f142_source_name,
                                                   f142_timestamp)
                test_message_queue.put(FakeMessage(f142_test_message))
                senv_values = np.array([26, 127, 52])
                senv_timestamp_ns = 123000  # ns after epoch
                senv_timestamp = datetime.datetime.fromtimestamp(senv_timestamp_ns * 1e-9,
                                                                 datetime.timezone.utc)
                senv_time_between_samples = 100  # ns
                senv_test_message = serialise_senv(senv_source_name, -1, senv_timestamp,
                                                   senv_time_between_samples, 0,
                                                   senv_values, Location.Start)
                test_message_queue.put(FakeMessage(senv_test_message))
                tdct_timestamps = np.array([1234, 2345, 3456])  # ns
                tdct_test_message = serialise_tdct(tdct_source_name, tdct_timestamps)
                test_message_queue.put(FakeMessage(tdct_test_message))
    
            n_chunks += 1
    
        assert isclose(data_from_stream.attrs[f142_source_name].value.values[0], f142_value)
        assert data_from_stream.attrs[f142_source_name].value.coords['time'].values[
            0] == np.array(f142_timestamp, dtype=np.dtype('datetime64[ns]'))
>       assert np.array_equal(data_from_stream.attrs[senv_source_name].value.values,
                              senv_values)
E       assert False
E        +  where False = <function array_equal at 0x7f4d6ef4b790>(array([], dtype=float64), array([ 26, 127,  52]))
E        +    where <function array_equal at 0x7f4d6ef4b790> = np.array_equal
E        +    and   array([], dtype=float64) = <scipp.DataArray>\nDimensions: Sizes[senv_source:0, ]\nCoordinates:\n  time                    datetime64             [ns]  (senv_source)  []\nData:\n                            float64  [dimensionless]  (senv_source)  []\n\n.values
E        +      where <scipp.DataArray>\nDimensions: Sizes[senv_source:0, ]\nCoordinates:\n  time                    datetime64             [ns]  (senv_source)  []\nData:\n                            float64  [dimensionless]  (senv_source)  []\n\n = <scipp.Variable> ()  DataArray  [dimensionless]  [<scipp.DataArray>\nDimensions: Sizes[senv_source:0, ]\nCoordinates:\n  ...64             [ns]  (senv_source)  []\nData:\n                            float64  [dimensionless]  (senv_source)  []\n\n].value

tests/test_data_stream.py:436: AssertionError
```

Edit: inconsistent tests fixed by commit https://github.com/scipp/scippneutron/pull/116/commits/cb439407aa8fa2991a5cb647327c7467615c1fd0 . I ran the tests approx 50 times to check stability, without this change they were previously failing ~20% of the time (in a relatively slow VM)

2021-09-14 14:16 UTC, Tom-Willemsen commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
I can't run this code snippet at all, when trying to run the cell I get:

```
Kernel Restarting
The kernel for Untitled1.ipynb appears to have died. It will restart automatically
```

2021-09-28 15:18 UTC, Tom-Willemsen commented on docs/developer/data-stream.rst
>          streaming_task = asyncio.create_task(my_stream_func())
This was because my VM didn't have enough memory. With an 8GB VM this is no longer a problem.

2021-09-28 15:40 UTC, Tom-Willemsen reviewed
Seems to functionnaly work ok for me now, with the few minor changes I've committed.

I do get a warning as mentioned in a previous comment about a message with unrecognised flattbuffer ID, but I would suggest merging thisand dealing with that warning in a seperate issue, so that this rather old PR can be merged.

2021-09-30 13:39 UTC, nvaytet approved these changes
Can you merge/rebase on `main` before we merge?
Thanks for sorting this one out! :+1:

2021-09-30 13:40 UTC, merged