Use conan for C+ deps
scipp/scippneutron pull request #118
Opened 2021-07-20 07:36 UTC by SimonHeybrock

Changes nearly identical to what we did in scipp.

2021-07-20 14:42 UTC, OwenArnold commented on python/CMakeLists.txt
> +pybind11_strip(_scippneutron)
What is the purpose of these calls?

2021-07-20 14:44 UTC, OwenArnold commented on python/CMakeLists.txt
> +pybind11_strip(_scippneutron)
I see what cmake_strip is doing and think I understand this now.

2021-07-20 14:47 UTC, SimonHeybrock commented on python/CMakeLists.txt
> +pybind11_strip(_scippneutron)
See https://pybind11.readthedocs.io/en/stable/compiling.html#findpython-mode. It is needed since we don't use `pybind11_add_module` anymore.

2021-07-20 15:12 UTC, OwenArnold requested changes
I manage to get this to work only with cmake 3.12 locally. For reasons similar to those explained here https://github.com/scipp/scipp/pull/2063

I wanted to make a similar modification to the environments but there are dependency conflicts between cmake 3.12 and mantid-framework we need to understand first.

Other than that, I think these changes are fine and I can build scippneutron locally

2021-07-22 13:37 UTC, OwenArnold requested changes

2021-07-22 13:37 UTC, OwenArnold commented on CMakeLists.txt
> +find_package(GTest REQUIRED)
```suggestion
find_package(GTest CONFIG REQUIRED)
```

2021-07-22 13:38 UTC, OwenArnold commented on CMakeLists.txt
> +find_package(GTest REQUIRED)
See https://github.com/scipp/scipp/pull/2063 and https://gitlab.kitware.com/cmake/cmake/-/issues/17365

2021-07-22 14:13 UTC, merged