Add single ToF bin around event data
scipp/scippneutron pull request #127
Opened 2021-08-05 21:24 UTC by Tom-Willemsen

For https://github.com/scipp/scippneutron/issues/112

2021-08-11 07:38 UTC, OwenArnold requested changes

2021-08-11 07:38 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +    _tof_edges = sc.Variable(
minor: use `sc.array`

2021-08-11 07:38 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +    _min_tof = min(
I guess you do it like this because we could have multiple nxevent_data groups and concatenating before taking the sc.min would be wasteful?

2021-08-11 07:38 UTC, OwenArnold commented on python/tests/test_load_nexus.py
>          np.sort(
Is `sc.identical(sc.sort(...), sc.sort(...))` too slow?

2021-08-11 07:38 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +    _tof_edges = sc.Variable(
minor: use `sc.array`

2021-08-11 07:38 UTC, OwenArnold commented on python/tests/test_load_nexus.py
> +    assert len(loaded_data.coords["tof"]) == 2
FYI, can use `shape` rather than `len`

2021-08-12 13:01 UTC, Tom-Willemsen commented
> Did you benchmark the performance of this? I am wondering if we lose much time in case the user binds in tof right after loading anyway.

I just ran some benchmarks. There is a bit of fluctuation, but on this branch the average on my machine for loading `SANS2D_ESS_Example1.nxs` is approx 1.8 seconds. On `main`, it takes approx 1.7 seconds.

> Or is the time dominated by mantid anyway?

This is the "pure scipp" loader; it is not using mantid.

2021-08-12 13:07 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +    _min_tof = min(
It hadn't occured to me to try concatenating before binning. Do you think there would be an advantage to that approach? Happy to try it if so.

2021-08-17 07:45 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +    _min_tof = min(
It is deliberate that the loader concatenates NXevent_data groups *after* binning. If we did it the other way round it would be significantly less efficient (Matt has tried and tested this during the original implementation, and confirmed the expected performance difference).

2021-08-17 08:13 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        _max_tof = float("inf")
Why do you need INF here instead of what you get from the function?

2021-08-17 08:14 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        values=[_min_tof, _max_tof + 1],  # +1 so that bins include all data
Can you just add a float epsilon? 1 can be quite large, depending on the context.

2021-08-17 08:15 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +                    edges=[_tof_edges])
Can you please verify if this has performance implications? It might, since we are now "binning" in 2d instead of 1d. If it does, we can instead add the extra dim and coord afterwards.

2021-08-17 08:18 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +                    edges=[_tof_edges])
I looked at the performance in a comment above

> I just ran some benchmarks. There is a bit of fluctuation, but on this branch the average on my machine for loading SANS2D_ESS_Example1.nxs is approx 1.8 seconds. On main, it takes approx 1.7 seconds.

2021-08-17 08:20 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        _max_tof = float("inf")
Because otherwise min will be `double_max` and max will be `double_min`, which would be the wrong way round. I could just invert min and max in this case if you think that's cleaner.

2021-08-17 08:24 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        _max_tof = float("inf")
Hmm, have you tried if `plot()` works with INF boundaries?

2021-08-17 15:31 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        values=[_min_tof, _max_tof + 1],  # +1 so that bins include all data
I agree that this isn't ideal. However, I'm also not sure that we can just use floating-point `epsilon` directly as `value + epsilon` will only be larger than `value` if `value <= 1`

```
>>> 0.5 + np.finfo("float64").eps == 0.5
False
>>> 5 + np.finfo("float64").eps == 5
True
```

So in this example if we use `eps` we may run into the last values in the ToF bin being excluded.

Furthermore, the ToF data may not even be floating-point, it is allowed to just be integer, in which case the `+1` is the smallest we could use.

I've made it configurable as a constant but left it at 1 for now, happy to discuss further if you like

2021-08-17 15:33 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        _max_tof = float("inf")
On further reflection I decided to just swap the limits, `Inf` has a lot of potential edge-cases and pitfalls when using the data later on (e.g. the plotting one you mention)

2021-08-18 05:06 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        values=[_min_tof, _max_tof + 1],  # +1 so that bins include all data
Use https://numpy.org/doc/stable/reference/generated/numpy.nextafter.html

2021-08-18 05:07 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        values=[_min_tof, _max_tof + 1],  # +1 so that bins include all data
Apparently Python 3.9 will also have it: https://stackoverflow.com/a/61119174 (but we still require older versions).

2021-08-20 10:48 UTC, SimonHeybrock approved these changes
Looks good, but there is a conflict to resolve.

2021-08-24 12:19 UTC, OwenArnold approved these changes

2021-08-24 12:19 UTC, merged