Add beamline components to the instrument view
scipp/scippneutron pull request #129
Opened 2021-08-13 14:24 UTC by OwenArnold

**WIP** This is not complete

2021-08-17 09:37 UTC, nvaytet commented
I think I agree with @SimonHeybrock 's suggestion of moving this into the `ess` repo.

I initially thought that it would be ok to do some of the common things here, because the `source_position` and `sample_position` are already special keys we rely on for unit conversions, but actually this is also going away with the new way to handle conversions via the `transform_coords` method.

We would leave the instrument view as it is in scippneutron, so that one can still display non-ESS instruments, but if you want to load all the components for loki, the special keys should be defined on a per-instrument basis.

2021-08-17 09:53 UTC, nvaytet requested changes

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +def _cube(position, message, sz, color):
I find the variable naming a little obscure here.
- I think it is not necessarily a `cube`? the box can have different xyz extents?
- `sz` is not very explicit
- `message` sounds like it has some communication aspect, but in fact it's just the text to be displayed above the component?

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    geometry = p3.BoxGeometry(width=sz[0],
I think `sz[0]` is hard to follow. I would either make a dict `{height: 1, ...}` or just use 3 separate variables?

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    det_center = sc.mean(positions_var)
I think you can get this information from the camera, and then you wouldn't need to compute the mean anymore.

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    return np.max(np.array(beamline_comp_positions)) * 5.0
It's a little strange that `_add_beamline` returns a distance between beamline components.
Maybe you can reset the camera in place here? You may need to pass the camera in anyway, if you want to avoid using `positions_var` as suggested above?

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +        sample = scipp_obj.meta["sample_position"]
```suggestion
        sample_position = scipp_obj.meta["sample_position"]
```

2021-08-17 09:53 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +        source = scipp_obj.meta["source_position"]
```suggestion
        source_position = scipp_obj.meta["source_position"]
```

2021-08-19 05:31 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +                    also_plot=None,
How about `components` or something like that?

2021-08-19 10:39 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +                    also_plot=None,
![image](https://user-images.githubusercontent.com/1109536/130055030-fe4da136-d040-4b47-b759-5283e42686a4.png)
Not done yet, but this gives a flavour of how things would be done

2021-08-19 10:44 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +                    also_plot=None,
👍

2021-08-19 10:50 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    det_center = sc.mean(positions_var)
I did think of this, but was struggling to figure out how to read that information out of the camera. Camera has lookAt, but there doesn't seem to be a way that I could see to read this back without some complex logic based on the frustrum coordinates.

2021-08-23 13:34 UTC, nvaytet requested changes

2021-08-23 13:34 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    shapes = {"cube": _box, "cylinder": _cylinder, "disk": _disk_chopper}
Could we just name these `monitor`, `source`, `sample` `chopper` instead of `cube` and `box`, `cylinder` etc...
i.e. standardize the way each instrument represents a monitor and a sample?
Don't know if we also want to standardize the colors for each component?

2021-08-23 13:46 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    shapes = {"cube": _box, "cylinder": _cylinder, "disk": _disk_chopper}
Ok will do. My reasoning was that some instruments might have a preference on how they represented components of each type, i.e use a cube for the sample and a cylinder for the source interchangeably - I think we get more convenience with your approach so lets take that. I think plotting all these non-detector components as grey is sufficient. Maybe we can consider upgrading the colours if we get specific requests about this.

2021-08-23 14:16 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    shapes = {"cube": _box, "cylinder": _cylinder, "disk": _disk_chopper}
Hmm, might want to decouple the shape from the category (monitor, source, ...). Maybe just standardize the color<->category mapping?

2021-08-23 14:21 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    shapes = {"cube": _box, "cylinder": _cylinder, "disk": _disk_chopper}
Consider someone with an instrument with a unique component. We would constantly get new request ("I need analyzer crystals", "I need slits", "I need XYZ", ...). I feel *not* having hard-coded names (or exclusively hard-coded) would be the better option.

2021-08-25 14:56 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    shapes = {"cube": _box, "cylinder": _cylinder, "disk": _disk_chopper}
So do you want "not hard-coded" or "exclusively hard-coded"?
I didn't really get what was the conclusion.
I think you would slowly build a library of component representations, slits, etc.. and over time I don't think we will get more and more requests, just a bit to start with.

2021-09-02 04:39 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    if components and not isinstance(plot, PlotDict):
Is this meant to read `plt`? `plot` is just the function?

2021-09-02 07:31 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    if components and not isinstance(plot, PlotDict):
Yes, that's a bug.

2021-09-02 11:29 UTC, SimonHeybrock commented
Given that this is a new feature, I would assume that we will have to iterate on this. Potential further comments may thus be addressed at a later point, I'll merge so we can try this out in practice.

2021-09-02 11:30 UTC, merged