Copy docs from scipp
scipp/scippneutron pull request #13
Opened 2021-02-23 13:15 UTC by SimonHeybrock

Docs moved from scipp with minor updates and restructure. There is a lot to improve here to make this more user friendly and readable, but I suggest to leave that for a future step.

2021-02-23 14:13 UTC, OwenArnold requested changes

2021-02-23 14:13 UTC, OwenArnold commented on docs/about/about.rst
> +
Should say something about scippneutron
```suggestion
``scippneutron`` builds on top of ``scipp`` and provides features specific to handling and reducing data generated in neutron scattering facilities.	
A key example is "unit conversion", e.g., from time-of-flight to energy transfer in an inelastic neutron scattering experiment at a spallation-based neutron source.
```

2021-02-23 14:13 UTC, OwenArnold commented on docs/about/contributing.rst
> +If in doubt whether a feature falls within the scope of scippneutron please `ask on github <https://github.com/scipp/scippneutron/issues>`_ before implementing functionality, to reduce the risk of re
Question here: We have kept all issues central in scipp, even if relating to `ess` `scippneutron`, `scippwidgets`, etc. This is proposing distributing our issue handling.

2021-02-23 14:13 UTC, OwenArnold commented on docs/about/contributing.rst
> +
```suggestion
`ess <https://github.com/scipp/ess>`_ is an example codebase providing facility-specific algorithms
```

2021-02-23 14:13 UTC, OwenArnold commented on docs/about/release-notes.rst
> +* Functionality from ``scipp.neutron`` is not available in this package.
Expand on this maybe?

2021-02-23 14:13 UTC, OwenArnold commented on docs/conf.py
> +project = u'scipp'
scippneutron

2021-02-23 14:13 UTC, OwenArnold commented on docs/index.rst
> +`this page <https://github.com/scipp/scippneutron/issues?utf8=%E2%9C%93&q=label%3Aquestion>`_
See above, usage of issues

2021-02-23 14:13 UTC, OwenArnold commented on docs/user-guide/groupby.ipynb
> +    "events = sc.neutron.load(filename='PG3_4844_event.nxs', load_pulse_times=False)"
These docs relate to "old" scipp + neutron package.

2021-02-23 14:16 UTC, SimonHeybrock commented on docs/about/contributing.rst
> +If in doubt whether a feature falls within the scope of scippneutron please `ask on github <https://github.com/scipp/scippneutron/issues>`_ before implementing functionality, to reduce the risk of re
Yes, I think we should in the long run. If we truly want scipp to become generic and used by outside projects we should not have neutron/ess noise in there.

2021-02-23 14:17 UTC, SimonHeybrock commented on docs/about/release-notes.rst
> +* Functionality from ``scipp.neutron`` is not available in this package.
```suggestion
* Functionality from ``scipp.neutron`` is now available in this package.
  This includes in particular the instrument view and "unit conversions" for time-of-flight neutron sources.
```

2021-02-23 14:19 UTC, OwenArnold commented on docs/about/contributing.rst
> +If in doubt whether a feature falls within the scope of scippneutron please `ask on github <https://github.com/scipp/scippneutron/issues>`_ before implementing functionality, to reduce the risk of re
I agree about not having the noise. As a team we manage single set of  resources across multiple repositories, so we'll have to think about how we manage the backlogs and priorities on each of these repositories properly. I don't have a strong opinions about opening up issues on `scippneutron` for now.

2021-02-23 14:20 UTC, OwenArnold commented on docs/about/release-notes.rst
> +* Functionality from ``scipp.neutron`` is now available in this package.
👍

2021-02-24 10:43 UTC, SimonHeybrock commented
@OwenArnold I think I agressed your comments, but will be happy to address more in the inevitable follow-ups. Merging so we can see if this published correctly.

2021-02-24 10:43 UTC, merged