Fix units encoding error
scipp/scippneutron pull request #144
Opened 2021-08-20 16:17 UTC by Tom-Willemsen

Closes https://github.com/scipp/scippneutron/issues/140

This PR ensures that we always load string data with the encodings specified in the nexus file.

For ASCII-encoded data in the nexus file, it allows the common extended ascii (latin-1) format, but warns as this is technically unspecified behaviour. Data files from ISIS do sometimes use these extended ASCII code points (see example LET data file linked to ticket). Data marked as UTF-8 will still be loaded correctly using that encoding.

See also https://docs.h5py.org/en/stable/strings.html

2021-08-22 20:10 UTC, OwenArnold requested changes
Overall I think what you have done makes sense.

2021-08-22 20:10 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_hdf5_nexus.py
> +                          f"specified by the HDF5 or nexus standards and may therefore "
Minor point, we are using American English spelling on the project `behaviour` -> `behavior`

2021-08-22 20:10 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_hdf5_nexus.py
> +def cset_to_encoding(cset: int):
minor rename `_cset_to_encoding` also you are inconsistently applying type hinting for the return types in these functions, though you do for most arguments.

2021-08-22 20:10 UTC, OwenArnold commented on python/tests/nexus_helpers.py
> +    event_time_zero_unit: Optional[Union[str, bytes]] = "ns"
Minor: Might be worth defining this Union somewhere common as is heavily used - though maybe doesn't make it much shorter or clearer?

2021-08-23 06:37 UTC, SimonHeybrock commented on python/tests/nexus_helpers.py
> +    event_time_zero_unit: Optional[Union[str, bytes]] = "ns"
I'd rather have this explicit than having to look up another name.

2021-08-23 12:43 UTC, Tom-Willemsen commented on python/tests/nexus_helpers.py
> +    event_time_zero_unit: Optional[Union[str, bytes]] = "ns"
I think on balance I agree with @SimonHeybrock that it's easier to understand as is? I can see the arguments both ways though and happy to change if you feel strongly about it.

2021-09-01 13:46 UTC, SimonHeybrock commented
@OwenArnold Did you have more comments on this?

2021-09-01 15:02 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_hdf5_nexus.py
> +                      f"Assuming data is UTF-8 encoded but this may be incorrect.")
No, not aware of any facilities that do this. It's not actually allowed by the nexus standard. I've changed it to an error.

2021-09-02 06:21 UTC, merged