Instrument view dictionary
scipp/scippneutron pull request #161
Opened 2021-09-09 07:19 UTC by OwenArnold

Fixes #154 

Controlling text size is difficult and has not been implemented:
* Text size in pythreejs only controls the resolution within the Mesh.
* In order to determine proper scaling factors I need to know the coordinates of the entire scene. This is currently known to the model of the Plot3D, but is not exposed.

2021-09-09 13:02 UTC, nvaytet requested changes

2021-09-09 13:02 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    text_position = tuple(position.value + np.array([0, 0.7 * bounding_box[1], 0]))
(unrelated to this line)
One issue I have with the way the text is represented is that is shows up on just one face of the plane geometry, and when you rotate the camera, at some point the text disappears.
I think we should use a `Sprite`, like i did for the text along the outline box axes:
https://github.com/scipp/scipp/blob/main/python/src/scipp/plotting/figure3d.py#L266
Sprites are always facing towards the camera.

2021-09-09 13:02 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +def _add_to_scene(position, scene, shape, display_text, bounding_box, color, **kwargs):
Do we want to have an option for opacity also?

2021-09-09 13:26 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    text_position = tuple(position.value + np.array([0, 0.7 * bounding_box[1], 0]))
```Py
def _text_mesh(position, display_text):
    text = p3.TextTexture(string=display_text, color='black', size=300)
    text_material = p3.SpriteMaterial(map=text, transparent=True)
    size = 1.0
    return p3.Sprite(material=text_material,
                     position=position,
                     scale=[size, size, size])
```

2021-09-09 13:37 UTC, OwenArnold commented on docs/user-guide/instrument-view.ipynb
> +    "gem_da.coords['sample_position']=sc.vector(value=[0,1,0], unit=sc.units.m)\n",
Thanks @nvaytet that's a bug left over from some testing i was doing in the notebook I'll remove.

2021-09-09 13:38 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    text_position = tuple(position.value + np.array([0, 0.7 * bounding_box[1], 0]))
Thanks @nvaytet good suggestion

2021-09-09 13:40 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +def _add_to_scene(position, scene, shape, display_text, bounding_box, color, **kwargs):
Hmm, that might have uses should one want to show the vacuum tank of a SANS instrument of a component maybe? Are their other concrete examples you are thinking of?

2021-09-09 14:06 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +def _add_to_scene(position, scene, shape, display_text, bounding_box, color, **kwargs):
Yeah i was thinking if you have a component inside a component.
Once thing we might also consider doing it providing a 'wireframe' option?
It's quite easy to do with the `EdgesGeometry`:
```Py
def _cylinder(position, display_text, bounding_box, color, **kwargs):
    geometry = p3.CylinderGeometry(radiusTop=bounding_box[0] / 2,
                                   radiusBottom=bounding_box[0] / 2,
                                   height=bounding_box[1],
                                   radialSegments=12,
                                   heightSegments=12,
                                   openEnded=False,
                                   thetaStart=0,
                                   thetaLength=2.0 * np.pi)
    edges = p3.EdgesGeometry(geometry)
    mesh = p3.LineSegments(geometry=edges,
                           material=p3.LineBasicMaterial(color='#000000'))
    mesh.position = tuple(position.value)
```
![Screenshot at 2021-09-09 16-04-54](https://user-images.githubusercontent.com/39047984/132701051-4be29e76-df40-4617-9160-595f21d7710f.png)

2021-09-09 14:08 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    text_position = tuple(position.value + np.array([0, 0.7 * bounding_box[1], 0]))
There seems to be some duplication between the different component types (setting the material, the position, creating the text).
Can we move the common functionality to a single function?

2021-09-09 14:14 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +def _add_to_scene(position, scene, shape, display_text, bounding_box, color, **kwargs):
How would we enable this in the API? it makes other features invalid, for example fill color settings. It looks like a nice setting, but I'm not sure how to get this to sit alongside the other input arguments we have.

2021-09-09 14:31 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +def _add_to_scene(position, scene, shape, display_text, bounding_box, color, **kwargs):
the color could just be the color of the wireframe?

2021-09-10 03:42 UTC, SimonHeybrock requested changes

2021-09-10 03:42 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
- Can you use newlines after each sentence, for a nicer diff?
- Use bullet point list to describe the various keys?
- Should describe `size` better, i.e.,that it should be a scalar variable with length unit.
- `at` sounds a bit odd to my ears, how about `center`?
  - We should also support accepting a (scalar) variable defining the center here. 
- How to get the list of supported shape types? You list a couple, but it is worded as if there were more?
- You say `wireframe` can be set to `True`, but also that it "provides a wireframe to represent the shape", which of the two is it?

2021-09-10 03:42 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +                f"but size has unit {size.unit}")
I suggest to not fail here, just use:
```python
component_position = sc.to_unit(component_position, positions.unit, copy=False)
size = sc.to_unit(size,  positions.unit, copy=False)
```
Note that we also need the former because:
- `sample_position` may have different unit from (detector) `position`
- `component_position` may be user-provided (see my other comment).

2021-09-10 17:47 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
I think `at` is ok, but i also don't mind `center`.

I don't think there is too much of an issue with the wireframe description. Maybe just something like
"`wireframe` is a bool that defaults to `False`. If set to `True`, the returned geometrical shape is a wireframe instead of a shape with opaque faces." ?

2021-09-13 07:30 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +                f"but size has unit {size.unit}")
For scipp 0.7, we cannot use `copy` and `to_unit` does not work on vector types. Otherwise I would implement this. I think it would be well worth doing this when we can develop scippneutron against 0.8 scipp.

2021-09-13 07:33 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
> How to get the list of supported shape types? You list a couple, but it is worded as if there were more?
I wrote this in a way such that we would not have to constantly update the docs when new shape types were added. The only way currently to see the supported shape types is to read the exception message for a failed type parameter - I think having a separate function to list the shape types would be useful.

2021-09-13 07:34 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +                f"but size has unit {size.unit}")
Given that the release is imminent: I was discussing with @jl-wynen last week that we will likely split the scippneutron release:
1. Release changes that have gone in so far + fixes from `scipp-0.8` branch.
2. Shortly after, release again with refactor of `convert` to use `sc.transform_coords`.

So if this PR can wait a couple days you could include it only in the second release.

2021-09-13 07:35 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
I am fine with the exception message, but maybe reformulate such that it is clear that this is the full list?

2021-09-13 07:36 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
(or maybe I mix this up with the formulation of the docstring, nevermind)

2021-09-13 10:44 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +    to False, but if set True, provides a wireframe to represent the shape.
I'm not sure the best pythonic way to do this, so i've added a `instrument_view_shape_types` function. `instrument_view` shares implementation with this, but it allows the user to query the supported shape types.

2021-09-13 10:44 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
> +                f"but size has unit {size.unit}")
Yes it can wait. Sounds reasonable to me.

2021-09-16 06:25 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +                f"but size has unit {size.unit}")
Since `main` is now compatible with `scipp-0.8` these changes can be implemented, even without `scippneutron` release.

2021-09-17 06:19 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +        component_position = scipp_obj.meta[center]
`center` should take a variable as an argument, not the name of an coord/attr (or in addition to). Otherwise you will not be able to display, say, monitor positions where you need to access `da.attrs['monitor'].value.meta['position']`.

2021-09-17 06:20 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
>      item, max_displacement = sorted(distances, key=lambda x: x[1])[-1]
Do we actually want to do this? Typically we want to just show the detectors, including the source 160 m away from a small detector in the view will make it almost unusable.

2021-09-17 07:20 UTC, OwenArnold commented on python/src/scippneutron/instrument_view.py
>      item, max_displacement = sorted(distances, key=lambda x: x[1])[-1]
The only thing this does is set the furthest distance the camera will support. Without this you will not ever be able to see the furthest components when you zoom out. Nevertheless, I'll refactor this slightly as some of the functionality it supports is no longer required.

2021-09-17 07:21 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
>      item, max_displacement = sorted(distances, key=lambda x: x[1])[-1]
👍 (I thought this would affect the default viewport)

2021-09-17 10:52 UTC, nvaytet requested changes

2021-09-17 10:52 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +        component_position = scipp_obj.meta[center]
I agree that `center` should just be a Variable, like `size`.

2021-09-17 10:52 UTC, nvaytet commented on python/src/scippneutron/__init__.py
> +from .instrument_view import instrument_view, instrument_view_shape_types
I think it's a bit overkill to make this function available to the user.
Could we just list the shapes in the docs, and in the instruement_view docstring?
I know it makes it more prone to having the code and the docs getting out of sync at some point, but I think it's not providing enough functionality to warrant a top-level function?
Once we put the function out there, it's more difficult to remove it later.

2021-09-17 10:52 UTC, nvaytet commented on docs/user-guide/instrument-view.ipynb
> +    "                    components={'sample': sample_settings, 'source': source_settings})"
Could you also add a couple of tests in the python tests (either in the `test_neutron.py` or move instrument view tests to a new file?) that test the new features (e.g. all the shapes, `wireframe=True` etc...).
As we probably don't want to test all the combinations in the docs...

2021-09-20 12:14 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +        return sc.geometry.position(x=center, y=center, z=center)
`center` is a bit misleading as a variable name? Isn't it `size`?

2021-09-21 09:43 UTC, nvaytet requested changes

2021-09-21 09:43 UTC, nvaytet commented on docs/user-guide/instrument-view.ipynb
> +    "                   'size': sc.vector(value=[1000, 2000, 1000], unit=sc.units.m), 'type': 'cylinder'}\n",
2km seems to be a very large size?

2021-09-21 09:43 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
>      text = p3.TextTexture(string=display_text, color='black', size=20)
The resolution on the text is quite bad, I would suggest to use `size=300`, as we do in the scipp 3d plotting.
![Screenshot at 2021-09-21 11-25-42](https://user-images.githubusercontent.com/39047984/134147146-fa5a8f4c-465a-4884-88a8-304ae88c2f5b.png)

2021-09-21 09:43 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
>  def _text_mesh(position, display_text, x_width, y_width):
I know i'm being annoying but it's not really making a `mesh` anymore, it's making a `Sprite`.
Rename to `_text_sprite` and `_create_text_sprite`? Or just `_create_text`?

2021-09-21 09:43 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +    text_mesh = _text_mesh(text_position,
Is `_text_mesh` being called anywhere else? If not, maybe we can drop the extra function and put everything in a single function named `_create_text`?

2021-09-21 09:43 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +                           x_width=max(bounding_box),
Also, I don't see `x_width` and `y_width` being used inside `_text_mesh`? (this is not picked up by `flake8`?)

2021-09-21 09:43 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +        furthest_distance = _furthest_component(det_center, scipp_obj, components)
For some reason, this seems to not quite be working. In the GEM example in the notebook above, I can't see the source. Only the sample in the middle of the detectors.

As an aside, when we rescale this, do we also want to rescale the red/green/blue axes? I think we currently don't have easy control over this in the plot. Maybe something for later?

2021-09-21 09:43 UTC, nvaytet commented on python/tests/test_instrument_view.py
> +            components={'sample': _make_component_settings(type='trefoil_knot')})
Maybe also test the `cylinder` and the `disk` to make sure these continue to work?

2021-09-21 09:44 UTC, nvaytet commented on python/src/scippneutron/instrument_view.py
> +        furthest_distance = _furthest_component(det_center, scipp_obj, components)
hmm maybe the fact that I can't see it is due to the gigantic size set in the notebook? (1x2x1 km)

2021-09-21 18:36 UTC, nvaytet approved these changes

2021-09-21 18:37 UTC, nvaytet commented
Thanks for all the changes. Looking good now :+1:

2021-09-22 03:33 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
> +        component_position = scipp_obj.meta[center]
@OwenArnold There is this comment left to address.

2021-09-22 09:09 UTC, SimonHeybrock commented on python/src/scippneutron/instrument_view.py
>      taken from.
This sentence does not parse anymore.

2021-09-22 09:15 UTC, SimonHeybrock approved these changes
Nice work, looks good. 👍

2021-09-22 10:08 UTC, merged