Load intermediate detector structures
scipp/scippneutron pull request #163
Opened 2021-09-10 12:43 UTC by Tom-Willemsen

Add option to load intermediate detector and event data structures directly as they appear in the nexus file, with no binning/preprocessing.

Closes https://github.com/scipp/scippneutron/issues/138

2021-09-13 07:12 UTC, SimonHeybrock reviewed
Some questions below. Happy to discuss in a call to clarify a bit more.

2021-09-13 07:12 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/load_nexus.py
> +                                         nexus_file, nexus, quiet)
I had expected that both of these use the same underlying code to load `NXevent_data`. As it is now there is a lot of duplication with `load_raw_detector_structure`, I think. Conceptually I thought this would look something like this:

```python
event_data = load_event_data(...)
if group_by_pixel:
  loaded_data = sc.bin(event_data, groups=[detector_id])
else:
  events = sc.DataArray(data=sc.ones(...), coords={'tof':event_data['tof'], 'pulse_time':event_data['pulse_time']})
  loaded_data = sc.bins(begin=event_data['event_index'], end=..., dim='pulse', data=events)
```
where the first three lines is what the existing implementation does.

Needs some extra thought w.r.t. how multiple banks get handled, but if all banks have the same pulses it can just be concatenated.

2021-09-13 14:40 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        loaded_data[name] = sc.scalar(value=data)
For symmetry with `load_data` without the `raw_detector_data` flag. I thought it would be confusing to return a `Dict` in one case and a `Dataset` in the other? As it is I think it is already slightly confusing as it can sometimes return a `DataArray` instead of a `Dataset`...

2021-09-13 14:45 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/load_nexus.py
> +                                         nexus_file, nexus, quiet)
Hmm, perhaps we had different ideas of what this ticket should accomplish? I thought we were trying to load the detector structures exactly as they appear in the nexus file, with no manipulations done at all. This way people can apply whatever specific binning steps they need manually, using the low-level structures if needed.

2021-09-13 15:16 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/load_nexus.py
> +                                         nexus_file, nexus, quiet)
> Hmm, perhaps we had different ideas of what this ticket should accomplish? I thought we were trying to load the detector structures exactly as they appear in the nexus file, with no manipulations done at all.

No, not actually different ideas: The structure of `NXevent_data` is essentially the same structure scipp uses for binned data, so not actual manipulation is necessary, just putting things into the right place. I can explain in a call tomorrow if you like.

2021-09-15 18:27 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +                            values=np.append(data.event_index.values[1:],
Why not the zeroth element?

2021-09-15 18:27 UTC, OwenArnold commented on python/src/scippneutron/file_loading/load_nexus.py
> +    :param raw_detector_data: if True, loads detector and event data structures as they
What happens to the other information (meta data) in this case?

2021-09-15 18:27 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +        detector_data.event_index = sc.Variable(dims=[_event_dimension],
```suggestion
        detector_data.event_index = sc.array(dims=[_event_dimension],
```

2021-09-15 18:47 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/load_nexus.py
> +    :param raw_detector_data: if True, loads detector and event data structures as they
The metadata is loaded as usual.

2021-09-15 18:53 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +                            values=np.append(data.event_index.values[1:],
If the event index is
```
[0, 5, 10]
```

We want the first bin to be events `0-5`, i.e. the end of the first bin is the second element of the event index.

2021-09-16 03:49 UTC, SimonHeybrock requested changes

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +                detector_group, detector_data.detector_ids.shape[0], file_root, nexus)
Even if we do not bin into pixels, shouldn't we still load the positions?

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +                                             data.event_index.values[-1]))
Isn't this dropping the events from the last pulse? I think we have to append the total number of events as the final end index.

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            return sc.bin(data.events, groups=[data.detector_ids], edges=[_tof_edges])
Why is it now `data.detector_ids`?

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
>          events = sc.concatenate(events, new_events, dim=_detector_dimension)
If `raw` then `dim` should not be `detector_id` (or similar) but `bank` (or similar).

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +    return sc.DataArray(data=events) if raw else events
Why the wrapping in a data array?

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
>              new_events.coords['position'] = detector_data.pixel_positions
If `raw` then we should add the pulse times here instead. Note that we should *not* map pulse times into bins in the "raw" load (it wouldn't be raw any more). This happens in `_load_event_group`.

2021-09-16 03:49 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/load_nexus.py
> +                      raw_detector_data=raw_detector_data), streams
Would a better name for this parameter be `bin_by_pixel` or something like this?

2021-09-16 13:52 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +                                             data.event_index.values[-1]))
This is already being done as one of the manipulations in `_load_event_group` (see https://github.com/scipp/scippneutron/blob/main/python/src/scippneutron/file_loading/_detector_data.py#L219), unless I have misunderstood your comment?

2021-09-16 13:53 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +            return sc.bin(data.events, groups=[data.detector_ids], edges=[_tof_edges])
Because this is a nested function which takes `data` as it's argument, I felt this was less ambiguous than shadowing the name from the outer scope?

2021-09-16 14:54 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            return sc.bin(data.events, groups=[data.detector_ids], edges=[_tof_edges])
Sorry, I misread, you are right.

2021-09-16 14:55 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +                                             data.event_index.values[-1]))
But if that is the case, shouldn't you have:
```python
begins = data.event_index[:-1]
ends = data.event_index[1:]
```
?

2021-09-20 04:59 UTC, SimonHeybrock requested changes

2021-09-20 04:59 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        _raw_pulse_times_np = _raw_pulse_times.values
Why do we need to convert to numpy just to convert back to scipp?

2021-09-20 04:59 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +                              coords={"pulse_time": data.pulse_times["pulse", :-1]})
Why is the last pulse dropped? There should be the same number of bins as pulse times, unless the index setup is wrong. You said earlier that `data.event_index` already had been extended by one element, so `begin` and `end` above should have the same length.

2021-09-20 04:59 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            del da.coords["pulse_time"]
Copy and paste error? We don't want to map the pulse times to events, when just loading the raw detector structure.

2021-09-20 04:59 UTC, SimonHeybrock commented on python/tests/test_load_nexus.py
> -def test_does_not_load_events_if_time_zero_unit_not_convertible_to_s(
Why is this removed?

2021-09-20 07:26 UTC, Tom-Willemsen commented on python/tests/test_load_nexus.py
> -def test_does_not_load_events_if_time_zero_unit_not_convertible_to_s(
This test mixed structures that did and didn't contain pulse times, which then caused `concatenate` to fail with mismatched dimensions if you try to concatenate those structures together.

2021-09-20 07:28 UTC, SimonHeybrock commented on python/tests/test_load_nexus.py
> -def test_does_not_load_events_if_time_zero_unit_not_convertible_to_s(
But this seems unrelated to the current change. Are you saying the test was passing but for the wrong reason?

2021-09-20 11:52 UTC, Tom-Willemsen commented on python/tests/test_load_nexus.py
> -def test_does_not_load_events_if_time_zero_unit_not_convertible_to_s(
I think the difference is probably that it is now a `coord`, where it was previously an `attr`? Not completely sure, I can look at this a bit further

2021-09-20 12:26 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
>          events = sc.concatenate(events, new_events, dim=_detector_dimension)
I'm not sure I understand exactly what is meant by this - we don't currently load `bank` as a dim/attribute and it's not clear to me exactly what this refers to. Should `bank` be the name of the nexus group from which the events were loaded (something like `detector_1_events`), or is there some other property that I've missed here?

2021-09-20 12:30 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
>          events = sc.concatenate(events, new_events, dim=_detector_dimension)
If we load multiple `NXevent_data` groups you end up callong `concatenate` here, and thus you need a dimension to concatenate along. I don't think there is a named equivalent to this in the file, since the file just uses multiple groups, rather than an axis/dimension, so the naming is slightly arbitrary.

We don't necessarily need a coord for this dim, but adding the Nexus group name as you suggest (`detector_1_events`) could be an option. But maybe just don't for now, for simplicity.

2021-09-20 12:34 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times_sc, sc.units.s, copy=False)
Wondering why the pulse-times get converted to seconds? While this was not introduced in this PR this seems wrong, since we lose a lot of very significant and important digits. @OwenArnold I think you reviewed the original PR that added this, can you comment?

2021-09-20 12:51 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times_sc, sc.units.s, copy=False)
I also think this is wrong, was just about to create an issue for it and assign myself.

2021-09-20 12:52 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times_sc, sc.units.s, copy=False)
https://github.com/scipp/scippneutron/issues/167

2021-09-20 13:50 UTC, OwenArnold commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times_sc, sc.units.s, copy=False)
Agree this should not be converted to seconds.

2021-09-22 03:35 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times, sc.units.ns, copy=False)
Why are we not simply leaving it in the original unit, as found in the file?

2021-09-22 03:37 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            dims=[_event_dimension if times_per_event else _pulse_dimension],
Aren't we in the `else:` branch of `if times_per_event` (unless I misread the diff)?

2021-09-22 03:38 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
>              dims=[_event_dimension if times_per_event else _pulse_dimension],
Aren't we in `if times_per_event`?

2021-09-22 03:40 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            dtype=sc.dtype.int64)
Not sure I understand what is done here. Why are we extracting values from a variable, just to create a new one?

2021-09-22 03:48 UTC, SimonHeybrock commented on python/tests/test_load_nexus.py
> +                   _time) <= np.array(1).astype("timedelta64[ns]"))
Use `isclose` or `allclose`?

2021-09-22 03:49 UTC, SimonHeybrock commented on python/tests/test_load_nexus.py
> +                  _time) <= np.array(1).astype("timedelta64[ns]")
Use `sc.allclose`?

2021-09-23 07:43 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +        pulse_times = sc.to_unit(_raw_pulse_times, sc.units.ns, copy=False)
Yes, exactly. The example files I have all use `s` in the nexus file,

2021-09-23 07:44 UTC, Tom-Willemsen commented on python/src/scippneutron/file_loading/_detector_data.py
> +            dtype=sc.dtype.int64)
To convert to `int64` so that we can add it to a `datetime64`. We don't want to load it initially as `int64` as we wouldn't have done the unit conversion yet and so may lose precision if the unit in the file is e.g. seconds

2021-09-23 07:44 UTC, Tom-Willemsen commented on python/tests/test_load_nexus.py
> +                   _time) <= np.array(1).astype("timedelta64[ns]"))
`isclose`/`allclose` don't support datetime64.

2021-09-23 07:44 UTC, Tom-Willemsen commented on python/tests/test_load_nexus.py
> +                  _time) <= np.array(1).astype("timedelta64[ns]")
`isclose`/`allclose` don't support datetime64.

2021-09-23 07:48 UTC, SimonHeybrock commented on python/src/scippneutron/file_loading/_detector_data.py
> +            dtype=sc.dtype.int64)
Use `astype`?

2021-09-23 07:53 UTC, SimonHeybrock commented on python/tests/test_load_nexus.py
> +                   _time) <= np.array(1).astype("timedelta64[ns]"))
Do we even have rounding issues then? Have you tried `sc.identical`?

2021-09-23 09:17 UTC, Tom-Willemsen commented on python/tests/test_load_nexus.py
> +                   _time) <= np.array(1).astype("timedelta64[ns]"))
Yes, I tried `sc.identical`. It fails on some tests because the numbers are not quite equal, hence the 1ns tolerance that I added in these tests.

2021-09-23 09:28 UTC, SimonHeybrock approved these changes

2021-09-23 10:39 UTC, merged