Add "Understanding Event Data" tutorial
scipp/scippneutron pull request #170
Opened 2021-09-23 12:06 UTC by SimonHeybrock

Mostly done. The last section (setting up data) will be removed in the final version, once we decided how to get data.

2021-09-23 12:40 UTC, OwenArnold requested changes
I've read through but not run this notebook yet. I'll do that next.

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "We use data containing event data form the POWGEN powder diffractometer at SNS.\n",
```suggestion
    "We use data containing event data from the POWGEN powder diffractometer at SNS.\n",
```

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "filename = 'PG3_4844_event.h5'\n",
Where would I know where to get this file from if I were just reading the documentation, i.e. downloading and running the notebook on my own as you suggest above?

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "The meaning of these can best be understood using a graphical depection of `da`, creating using `sc.show`:"
```suggestion
    "The meaning of these can best be understood using a graphical depection of `da`, created using `sc.show`:"
```

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "For dense data this might give us a `float` value, for binned data we obtain a table:"
"Binned data is a precursor to dense or histogrammed data" but is also useful in its own right to do things that you cannot properly do with histogrammed data, such as resampling.

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "Once we have summed the bin values there are no more bins, and the `bins` property is `None`:"
You might want to explicitly say that what you have is histogrammed so that users understand the results are the same, thought I see you don't introduce that until option 2.

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "# Start and stop are ficticious and this prompt pulse is not actually present in the raw data from SNS\n",
```suggestion
    "# Start and stop are fictitious and this prompt pulse is not actually present in the raw data from SNS\n",
```

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "- Adopt the code of the 1-D cut to create 100 `two_theta` bins.\n",
```suggestion
    "- Adapt the code of the 1-D cut to create 100 `two_theta` bins.\n",
```

2021-09-23 12:40 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "import scipp as sc\n",
Partially answers my question above about the input file, though users might also want to know where to get the nexus file from.

2021-09-23 12:42 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "filename = 'PG3_4844_event.h5'\n",
We are still discussing how to best to this, either traditional solution (add link, as in other tutorials) or download in the notebook.

2021-09-24 03:35 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "Once we have summed the bin values there are no more bins, and the `bins` property is `None`:"
👍

2021-09-24 03:38 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "For dense data this might give us a `float` value, for binned data we obtain a table:"
👍

2021-09-24 08:46 UTC, OwenArnold requested changes
Comments from executing tutorial

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "sc.show(da)"
![image](https://user-images.githubusercontent.com/1109536/134640652-1fff54a3-cda0-4a03-b71f-b4cddd056d1f.png)

Some of the text is very small. Likely as scipp issue to fix this.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "2. An array of bins (such as the array a yellow cubes with dots above) is referred to as *binned variable*.\n",
```suggestion
    "2. An array of bins (such as the array a yellow cubes with dots, shown above) is referred to as *binned variable*.\n",
```

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "Instead each bin refers to a section (slice) of a long table containing all the events from all bins combined.\n",
Missing sentence might help to ensure users really understand what we are saying.

```We internally we these slices "views", which alias sections of the full event table.```

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "da.values[500]"
Maybe explicitly say what 500 here refers to to ensure users are still following.

Maybe also explain what the limits are here. Why indexes need to be >= 0 and < 24794 based on the html output above. Or you could move this to the exercise as a question.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +   ]
Possible to introduce a question(s) at this point. for example why does the representation have two yellow columns for the data.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "sc.table(spec.values[0]['event',:5])"
This is good, but might want to ensure that all the readers understand the indexing and slicing performed up to this point. i.e. say something explicitly about the bin and the events from the bin requested.

Related, you should probably say something about the sort order in the visualisation, particularly with reference to the TOF as this might come up as a question in relation to the histogramming.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "prompt_stop = 5000.0 * sc.Unit('us')\n",
finding the prompt pulse would be an interesting exercise, but maybe too advanced and too orthogonal to what you are trying to show here.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "spec1.bins.masks['prompt_pulse'] = (prompt_start <= event_tof) & (event_tof < prompt_stop)\n",
Are you comfortable that the people on the course have previously seen masking? For example users will need to be aware that operators on RHS yield boolean outputs that are assigned as masks. If not then it's maybe worth directing users to the masking tutorials in scipp.

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "Rather than masking individual events, let us simply \"sort\" the events dependig on whether they fall below, inside, or above the region of the prompt-pulse.\n",
```suggestion
    "Rather than masking individual events, let us simply \"sort\" the events depending on whether they fall below, inside, or above the region of the prompt-pulse.\n",
```

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "Rather than masking individual events, let us simply \"sort\" the events dependig on whether they fall below, inside, or above the region of the prompt-pulse.\n",
Say why this is not recommended

2021-09-24 08:46 UTC, OwenArnold commented on docs/tutorials/understanding-event-data.ipynb
> +    "binned_da = sc.bin(da, edges=[prompt_tof_edges, pulse_time_edges])\n",
Note `pulse_time_edges` would only be defined if the user had run the cell for the previous solution.

2021-09-24 08:51 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "Instead each bin refers to a section (slice) of a long table containing all the events from all bins combined.\n",
Reformulating as "Instead each bin is a view to a section (slice) of a long table containing all the events from all bins combined."

2021-09-24 08:52 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "da.values[500]"
Add `Here we access the 500th event list (counting from zero):`

2021-09-24 08:53 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +   ]
Maybe if it comes up? It distracts from the topic, since it is not really related?

2021-09-24 08:56 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "sc.table(spec.values[0]['event',:5])"
Added "Note the chained slicing above:
We access the zeroth event list and select the first 5 slices along the `event` dimension (which is the only dimension, since the event list is a 1-D table)."

2021-09-24 08:56 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "spec1.bins.masks['prompt_pulse'] = (prompt_start <= event_tof) & (event_tof < prompt_stop)\n",
This will run on day 2. We do the masking tutorial on day 1.

2021-09-24 08:56 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "spec1.bins.masks['prompt_pulse'] = (prompt_start <= event_tof) & (event_tof < prompt_stop)\n",
But I will add a link nevertheless.

2021-09-24 10:55 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "binned_da = sc.bin(da, edges=[prompt_tof_edges, pulse_time_edges])\n",
Not sure what the best way of handling this is. Do we want to provide notebooks without solutions? Then I agree that this would be a problem.

I am undecided as to what is the optimal solution. Making two versions of every notebook is too much overhead, but at the same time we don't have a fully working solution for hiding solutions at this point.

Thoughts @OwenArnold @nvaytet ?

2021-09-24 14:46 UTC, nvaytet commented on docs/tutorials/understanding-event-data.ipynb
> +    "The meaning of these can best be understood using a graphical depection of `da`, created using `sc.show`:"
```suggestion
    "The meaning of these can best be understood using a graphical depiction of `da`, created using `sc.show`:"
```

2021-09-24 14:46 UTC, nvaytet commented on docs/tutorials/understanding-event-data.ipynb
> +    "Note that the effect depected here was added artifically for the purpose of this tutorial and is likely much larger than what could be observed in practice from changes in sample environment par
```suggestion
    "Note that the effect depicted here was added artifically for the purpose of this tutorial and is likely much larger than what could be observed in practice from changes in sample environment parameters such as (pressure or temperature).\n",
```

2021-09-27 05:30 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "As usual, to begin exploring a loaded file, we can inspect the HTML representation of a scipp object shown by Jupyter when typing a variable at the end of a cell (this can also be done using `sc
I added it because then you can create multiple representations from the same cell. Isn't it also confusing that you don't get any output if a variable is not the last thing you write in a cell?

2021-09-27 05:35 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "We can use `da_bins_sum` to, e.g., plot the total counts per spectrum by summing over the `tof` dimension (in this case there is just a single time-of-flight bin so we could have used `da_bin_su
I see your point, but I also think it is important to make this clear, because otherwise "summing over 1 point" seems confusing. And while it may be confusing, it is important for the reader to understand and get beyond the confusion, since if they do not understand this they cannot understand the basic concepts of scipp.

I moved the parenthesis to after the code cell.

2021-09-27 05:38 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "# Start and stop are ficticious and this prompt pulse is not actually present in the raw data from SNS\n",
Yes, I feel it should be said. I has made it a comment in the code rather than the text since it is not crucial for the course material.

2021-09-27 05:40 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "sc.plot({'spec':spec_hist, 'prompt':prompt})"
Just a binning artifact. I increased the bin count to make this less apparent.

2021-09-27 05:46 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "If the existing binning is sufficient for our purpose we may simply sum over the rows of the tables making up the bin values:"
I suppose this is a language question. I read "sum over rows" as "Take all rows and add them together", i.e., `da.sum('row')`.

2021-09-27 05:48 UTC, SimonHeybrock commented on docs/tutorials/understanding-event-data.ipynb
> +    "sc.plot({'event-mask':spec1, 'bin-mask (1.1x)':spec2*sc.scalar(1.1)})"
We cannot slice since this is event data.

2021-09-27 11:28 UTC, SimonHeybrock commented
Thanks for the comments. I'll merge this so we can move forward, as always with docs pages there will undoubtedly be more iterations.

2021-09-27 11:28 UTC, merged