Use pooch to get tutorial data
scipp/scippneutron pull request #174
Opened 2021-09-27 12:14 UTC by SimonHeybrock

Use pooch instead of custom handling of sample data. They key advantage is that it makes notebooks portable, in particular also to our JupyterHub, and to users computers, without requiring manual file downloads.

For later:
- Use same approach for other files used in docs.
- Consider adding generated data, rather than just downloaded. Maybe more relevant for `scipp` itself.
- Are we happy with the naming?

2021-09-27 12:51 UTC, SimonHeybrock commented
@nvaytet Should we just version `scippneutron.data` independently, i.e., just define a version in `data/__init__.py` that gets updated only if we need to replace a file?

2021-09-28 07:24 UTC, nvaytet reviewed
A couple of questions, otherwise looks fantastically simple!

2021-09-28 07:24 UTC, nvaytet commented on docs/tutorials/exploring-data.ipynb
> +    "data = scn.data.tutorial_dense_data()"
Can we make sub-groups in the `.data`, e.g. `scn.data.tutorials.dense_data()`?
Or something like a dict that would let us list the keys to see what's available?

2021-09-28 07:24 UTC, nvaytet commented on python/src/scippneutron/data/__init__.py
> +        base_url='https://public.esss.dk/groups/scipp/scippneutron/{version}/',
I'm not sure exactly why we need the version here. Does `pooch` require versions to work?
Or is it because you think the files might change in the future and you want to maintain backward compatibility?

2021-09-28 07:25 UTC, SimonHeybrock commented on docs/tutorials/exploring-data.ipynb
> +    "data = scn.data.tutorial_dense_data()"
Probably some combination of the above. I think it hard to come up with a good solution with only two examples, so I suggest to refactor once we have more.

2021-09-28 07:27 UTC, SimonHeybrock commented on python/src/scippneutron/data/__init__.py
> +        base_url='https://public.esss.dk/groups/scipp/scippneutron/{version}/',
The pooch docs highly recommend using versions. And I think it does make sense. For example we might want to change tutorials from using data with fake artifacts/filtering to data where we can filter on something real. We still need to keep the old releases working.

2021-09-28 08:22 UTC, nvaytet requested changes

2021-09-28 08:22 UTC, nvaytet commented on docs/tutorials/exploring-data.ipynb
> +    "We  start by loading some data, in this case measured with a prototype of the [LoKI](https://europeanspallationsource.se/instruments/loki) detectors at the [LARMOR beamline](https://www.isis.stf
Can you split long lines while you're at it?

2021-09-28 08:22 UTC, nvaytet commented on docs/tutorials/working-with-masks.ipynb
> +    "We  start by loading some data, in this case measured with a prototype of the [LoKI](https://europeanspallationsource.se/instruments/loki) detectors at the [LARMOR beamline](https://www.isis.stf
Split long line

2021-09-28 08:24 UTC, SimonHeybrock commented on docs/tutorials/exploring-data.ipynb
> +    "We  start by loading some data, in this case measured with a prototype of the [LoKI](https://europeanspallationsource.se/instruments/loki) detectors at the [LARMOR beamline](https://www.isis.stf
What's wrong with once sentence per line?

2021-09-28 08:26 UTC, nvaytet commented on docs/tutorials/exploring-data.ipynb
> +    "We  start by loading some data, in this case measured with a prototype of the [LoKI](https://europeanspallationsource.se/instruments/loki) detectors at the [LARMOR beamline](https://www.isis.stf
One sentence per line is ok, but it's even easier to review if long sentences are split?

2021-09-28 08:28 UTC, SimonHeybrock commented on docs/tutorials/exploring-data.ipynb
> +    "We  start by loading some data, in this case measured with a prototype of the [LoKI](https://europeanspallationsource.se/instruments/loki) detectors at the [LARMOR beamline](https://www.isis.stf
You can split it next time you change the file ;)

2021-09-28 08:40 UTC, nvaytet approved these changes

2021-09-28 08:52 UTC, merged