Load transformations using new spatial transform data types
scipp/scippneutron pull request #200
Opened 2021-10-27 14:34 UTC by Tom-Willemsen

Use the new spatial transform types in loading component positions.

This is related to https://github.com/scipp/scippneutron/issues/34 but does not yet fully fix that issue as we need to discuss how we want transforms to appear to the user in their loaded dataset (currently the code just uses the first transform, effectively throwing away any subsequent values).

2022-01-21 06:34 UTC, SimonHeybrock requested changes

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +        times = sc.array(dims=["value"], values=[0.], unit=sc.units.s)
- Same question about dim label as above.
- Returning a dummy time of `0` does seem quite error prone. Can't we just return what we have, i.e., a scalar `magnitude` (similar to the current code), and handle differences downstream?

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                            copy=False)
Can use `to(unit=..., dtype=...)`

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                                    copy=False)
Can use `to()`

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +        value=direction_unit_vector) * sc.scalar(-1.0) * loaded_transform_m
```suggestion
    vectors = sc.vector(value=-direction_unit_vector) * loaded_transform_m
```
more readable?

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +    translations = translations * sc.spatial.translation(value=offset, unit=sc.units.m)
Having trouble understanding what is done in this function:
1. We load translation magnitudes
2. We create a vector from a direction and the translation magnitudes
3. We convert the vector into a translation
4. We create another translation from "offset"
5. We combine this with the first translation

I don't if I misunderstood, but this is very hard to see through?

Why not use plain addition to add the two offset vectors (convert to `translation3` only at the very end)?

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                     coords={"time": loaded_transform.coords["time"]}))
Why is our math dropping the coord? Because it has no choice since we currently do not support operations from `spatial` with data arrays?

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +        coords={"time": sc.array(dims=["value"], values=[0.], unit=sc.units.s)})
- As written elsewhere, we should probably work with datetimes, such as for other `NXlog`?
- This this to arbitrarily introduce an additional time point with no transform. With the interpolation below, couldn't this lead to completely broken results, e.g., if there is an actual transform just below 0 that is overridden by this?

Can we just initialize the output transform to the first (in time) transform and only multiply the remaining ones?

2022-01-21 06:34 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                      dim="value"), "value")
Doesn't this give bad results if there are multiple transforms at the same time? Should `xnew` avoid duplicates?

2022-01-21 09:19 UTC, jl-wynen commented on src/scippneutron/file_loading/_transformations.py
>      :return: Position of the component as a three-element numpy array
```suggestion
    :return: Position of the component as a three-element Variable
```

2022-01-21 09:19 UTC, jl-wynen commented on src/scippneutron/file_loading/_transformations.py
> +    return total_transform_matrix * sc.vector(value=[0, 0, 0], unit=sc.units.m)
Is it correct that this multiplication extract the translation part of the transform? We should add a nicer way of doing that in scipp.

2022-01-21 09:19 UTC, jl-wynen commented on src/scippneutron/file_loading/_transformations.py
>  def get_full_transformation_matrix(group: Group, nexus: LoadFromNexus) -> np.ndarray:
```suggestion
def get_full_transformation_matrix(group: Group, nexus: LoadFromNexus) -> sc.DataArray:
```
And in docstring

2022-01-24 21:35 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +                      dim="value"), "value")
Is there a convenient way to do this in scipp without converting to numpy and then back again? Or would it be worth me adding something like `sc.unique()` in scipp (acting like [`np.unique`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html))?

2022-01-25 05:14 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                      dim="value"), "value")
There is currently no way I think, i.e., you would indeed need to use `np.unique`. I think adding it in scipp would be ok (but that does not help you here, since you'd need to wait for the next release), but I'd use numpy for now.

2022-01-25 15:06 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +                     coords={"time": loaded_transform.coords["time"]}))
> Why is our math dropping the coord? Because it has no choice since we currently do not support operations from `spatial` with data arrays?

Yes, we don't have a function which converts vector -> translation as a data array, we only have constructors for `Variable`s with the spatial transform types.

2022-01-25 15:48 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +        times = sc.array(dims=["value"], values=[0.], unit=sc.units.s)
>     * Returning a dummy time of `0` does seem quite error prone. Can't we just return what we have, i.e., a scalar `magnitude` (similar to the current code), and handle differences downstream?

I'm not sure I understand what you're suggesting here. Do you mean that as a user I would have some transforms loaded as scalars and others as arrays along the `time` dimension? Isn't that confusing for the users - as a user I think I would expect a consistent return format?

Or did you mean something else by "handle the differences downstream"... in which case where is "downstream" in this instance?

2022-01-25 15:53 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +    return total_transform_matrix * sc.vector(value=[0, 0, 0], unit=sc.units.m)
I'll create a separate issue for this in scipp - we'll need to come up with a good non-ambiguous name for it.

2022-01-25 15:58 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +    return total_transform_matrix * sc.vector(value=[0, 0, 0], unit=sc.units.m)
Actually, on second thoughts, I'm not sure this makes sense? If we had a function like `sc.spatial.translation_component(transform)`, I think it would make sense for it to be returning `translation3` and not `vector3`, so we would still need to do another conversion from `translation3`->`vector3`? I'm now thinking it probably does make more sense to think of this as "appyling the transform to the zero vector" rather than "extracting the translation component". 

Happy to discuss if you disagree though?

2022-01-25 16:08 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_transformations.py
> +                                                 unit=sc.units.rad)
I think we did it like this to be consistent with all the other creation functions in the table at https://github.com/scipp/scipp/issues/2252#issuecomment-990864357 which take numpy types and return `Variable`. I think the consistency is good - but perhaps we should additionally have some kind of wrapper/helper that takes `Variable` as well to avoid the error-prone api? What do you think?

2022-01-26 04:38 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                                                 unit=sc.units.rad)
I think we want consistency for the *direct constructors* (`vectors`, `affine_transform`, ...), but `rotations_from_rotvecs` is somewhat "higher level" functionality (we could almost think of it as a variant of `astype()` -- I am not at all suggesting to combine it though). I think we should generally force users of scipp to use `Variable` wherever possible, eliminating as many sources of bugs as possible (while keeping the code and design simple).

2022-01-26 04:41 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +        times = sc.array(dims=["value"], values=[0.], unit=sc.units.s)
> Do you mean that as a user I would have some transforms loaded as scalars and others as arrays along the time dimension? Isn't that confusing for the users - as a user I think I would expect a consistent return format?

I think that is what I mean. I don't think it would add confusion (mutating what is in the file *does*). If some transform does not have `time` dimension then that's fine since scipp's automatic broadcasting can take care of it, can't it?

2022-01-26 04:43 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                     coords={"time": loaded_transform.coords["time"]}))
We should probably have a look if that can be alleviated.

2022-01-26 05:00 UTC, SimonHeybrock reviewed
Looks pretty good, a couple more comments below.

2022-01-26 14:47 UTC, Tom-Willemsen commented on src/scippneutron/file_loading/_detector_data.py
> +                                                                              0].data
Yes, this is basically a "hack" for the moment that keeps this code compatible with what we are currently returning. The next PR (not opened yet) removes this "hack" and returns the full transform dataarray + base position to the user.

2022-01-27 06:24 UTC, SimonHeybrock commented on src/scippneutron/file_loading/_transformations.py
> +                    transform, xnew) * _interpolate_transform(total_transform, xnew)
Why do we need to interpolate `total_transform`? If I understand correctly it is a variable (without time dim), so shouldn't this just be something like:
```suggestion
            if isinstance(transform, sc.DataArray):
                xnew = transform.coords["time"]
                total_transform = _interpolate_transform(transform, xnew) * total_transform
```
would that also obviate the branch in `_interpolate_transform` above?

2022-01-28 05:05 UTC, SimonHeybrock approved these changes

2022-01-28 07:44 UTC, merged