Support overriding beamline parameters
scipp/scippneutron pull request #26
Opened 2021-03-03 15:20 UTC by SimonHeybrock

Fixes https://github.com/scipp/scipp/issues/1672 (and more).

How does it work?
- All operations try to refer only to what the actually need to know, e.g., `L2` instead of `position` and `sample_position`. The helper functions `l2` can then figure out how to obtain it.
- Most explicit matching coords take priority.

Todo:
- Documentation
- Future: Considering to support providing overriding via arguments to `convert` rather than via coords, but this is more complicated, and could become easier if the ownership model is changed. I suggest to avoid this for now.

2021-03-04 12:01 UTC, SimonHeybrock commented
These are the dot graph I added to the docs:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/12912489/109960957-a9a02100-7ce9-11eb-93ad-96c86e8cbb93.png">

<img width="426" alt="image" src="https://user-images.githubusercontent.com/12912489/109960992-b1f85c00-7ce9-11eb-96f7-fed90d856668.png">

2021-03-04 12:19 UTC, jl-wynen commented
I take it, TOF is implicit in the graphs because there is no way to deduce like like, e.g. L1?

Would it make sense to have 'pixel_position' instead of just 'position' to avoid confusion? Or maybe support either when computing 'scattered_beam'?

2021-03-04 12:23 UTC, SimonHeybrock commented
> I take it, TOF is implicit in the graphs because there is no way to deduce like like, e.g. L1?

Well, partially. You can also convert from, e.g., `wavelength` to `energy`, then `tof` is not needed. So strictly speaking the graph should have all possible combinations of units, but that would be a bit messy.

> Would it make sense to have 'pixel_position' instead of just 'position' to avoid confusion? Or maybe support either when computing 'scattered_beam'?

The problem is that people use "detector", "pixel", and "spectrum" to describe the same or related concept. We do not want to support multiple ambiguous ways of specifying this. Which would take priority if someone has `pixel_position` and `spectrum_position`?

2021-03-04 12:30 UTC, jl-wynen commented
> So strictly speaking the graph should have all possible combinations of units, but that would be a bit messy.

Maybe, not sure how messy it would be. I was just confused how you want to get a wavelength from just 'Ltotal'.

> The problem is that people use "detector", "pixel", and "spectrum" to describe the same or related concept. We do not want to support multiple ambiguous ways of specifying this. Which would take priority if someone has pixel_position and spectrum_position?

Yes, I agree that we should not have a resolution order for different ways of saying the same thing. But is 'position' not ambiguous on its own?

2021-03-04 12:32 UTC, SimonHeybrock commented
> > The problem is that people use "detector", "pixel", and "spectrum" to describe the same or related concept. We do not want to support multiple ambiguous ways of specifying this. Which would take priority if someone has pixel_position and spectrum_position?
> 
> Yes, I agree that we should not have a resolution order for different ways of saying the same thing. But is 'position' not ambiguous on its own?

Not ambiguous, because `position` is actually a coordinate for a dimension of the data (often the dimension is called `spectrum`), whereas `sample_position` and `source_position` are scalar coordinates.

2021-03-04 12:34 UTC, jl-wynen commented
What if the detector can be moved and every event is recorded at a different position? Maybe someone understands 'position' as the position of the robot arm? Or the sample gets moved?

Don't know if this can really cause confusion in practice.

2021-03-04 12:36 UTC, SimonHeybrock commented
> What if the detector can be moved and every event is recorded at a different position? Maybe someone understands 'position' as the position of the robot arm? Or the sample gets moved?
> 
> Don't know if this can really cause confusion in practice.

In those cases there would be an *additional* dimension, e.g., `sample_position`, and `sample_position` would become a dimension-coord of that dim. `position` is still unambiguously a coord of `spectrum` dim.

2021-03-04 13:13 UTC, SimonHeybrock commented
> > So strictly speaking the graph should have all possible combinations of units, but that would be a bit messy.
> 
> Maybe, not sure how messy it would be. I was just confused how you want to get a wavelength from just 'Ltotal'.

Even with *only* conversion from tof, it get much less readable and useful, I think: 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/12912489/109968987-a6aa2e00-7cf3-11eb-9efa-a4ba38a72edc.png">

If you really wanted to do this you would need a separate figure for every possible pair of input and output unit.

2021-03-04 13:18 UTC, OwenArnold requested changes

2021-03-04 13:18 UTC, OwenArnold commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.node('Q', shape='box', style='filled', color='lightgrey')\n",
Q -> ||Q||

2021-03-04 13:18 UTC, OwenArnold commented on docs/user-guide/unit-conversions.ipynb
> +    "There are two case, scattering conversion and non-scattering conversion (e.g., for beam monitors or for imaging beamlines).\n",
```suggestion
    "There are two cases, scattering conversion and non-scattering conversion (e.g., for beam monitors or for imaging beamlines).\n",
```

2021-03-04 13:18 UTC, OwenArnold commented on docs/user-guide/unit-conversions.ipynb
> +    "The parameters given in the table above are retrived from the coordinates or attributes of the input data.\n",
```suggestion
    "The parameters given in the table above are retrieved from the coordinates or attributes of the input data.\n",
```

2021-03-04 13:18 UTC, OwenArnold commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.edge('two_theta', 'dspacing')\n",
Given you are creating dot diagrams for the docs. Maybe it's worth adding a simple schematic to show 2theta as a projection with source sample, detector?

2021-03-04 13:18 UTC, OwenArnold commented on neutron/beamline.cpp
> +  if (meta.contains(Dim("Ltotal")))
maybe move these names to be class/global variables. To prevent future bugs.

2021-03-04 13:18 UTC, OwenArnold commented on neutron/beamline.cpp
> +    return norm(meta[Dim("scattered_beam")]);
Redefining the meaning of l2 here https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/src/Instrument/DetectorInfo.cpp#L122-L132

2021-03-04 13:18 UTC, OwenArnold commented on neutron/beamline.cpp
>    if (scatter == ConvertMode::Scatter)
Linked to above ltotal = l1 + l2 with magnitude fixed to 2.

2021-03-04 13:20 UTC, SimonHeybrock commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.node('Q', shape='box', style='filled', color='lightgrey')\n",
The names here correspond to what you need to specify as an arg to convert, in this case `scn.convert(data, 'wavelength', 'Q')`, not ||Q||.

2021-03-04 13:22 UTC, SimonHeybrock commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.edge('two_theta', 'dspacing')\n",
I think the documentation linked at the top of the page does a better job at that and avoid duplicate efforts?

2021-03-04 13:23 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +    return norm(meta[Dim("scattered_beam")]);
I don't understand your comment?

2021-03-04 13:24 UTC, SimonHeybrock commented on neutron/beamline.cpp
>    if (scatter == ConvertMode::Scatter)
I don't understand your comment.

2021-03-04 13:26 UTC, OwenArnold commented on neutron/beamline.cpp
> +    return norm(meta[Dim("scattered_beam")]);
What you have is fine. I misunderstood what's happening here. returning magnitude nor normalising to (basis) vector.

2021-03-04 13:28 UTC, SimonHeybrock commented
Note that there is one more thing I need to add/fix here: Update mechanism for changing coord <-> attrs in the actual `convert` implementation.

2021-03-04 13:37 UTC, OwenArnold commented on neutron/beamline.cpp
> +  return acos(cos_two_theta(meta));
This whole mechanism seems good to me and gives good flexibility providing people know how to use it. I wonder if `convert` ought to have some kind of verbose mode where it was easy to determine what was being used. Maybe having the l1/l2 flight_path functions from beamline is enough for diagnostics though.

2021-03-04 13:39 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +  return acos(cos_two_theta(meta));
I think this would link into a larger discussion on logging by scipp. Not logging from `scipp` is maybe still what we want, but logging from `scippneutron` could be useful?

2021-03-04 13:41 UTC, OwenArnold commented on neutron/beamline.cpp
> +  return acos(cos_two_theta(meta));
I agree it's part of a larger discussion. I think users would be very grateful if they could more easily get extra logging information for some of the operations like `convert`

2021-03-04 14:29 UTC, SimonHeybrock commented
> Note that there is one more thing I need to add/fix here: Update mechanism for changing coord <-> attrs in the actual `convert` implementation.

Done, this should be ready now. As before I am quite unhappy about the coord<->attr swapping mechanism, but this is not really new and the only option we could come up with.

2021-03-04 19:33 UTC, OwenArnold commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.edge('two_theta', 'dspacing')\n",
It's certainly more thorough. I was hoping to see something very simple like this https://docs.mantidproject.org/nightly/_images/SpecularReflectionCorrection_figure1.png

2021-03-05 06:17 UTC, SimonHeybrock commented on docs/user-guide/unit-conversions.ipynb
> +    "dot.edge('two_theta', 'dspacing')\n",
We can certainly add figures (multiple would be need for the different cases), but this is outside the scope of the PR, I think.

2021-03-05 07:31 UTC, OwenArnold approved these changes

2021-03-05 07:36 UTC, SimonHeybrock commented
> > > So strictly speaking the graph should have all possible combinations of units, but that would be a bit messy.
> > 
> > 
> > Maybe, not sure how messy it would be. I was just confused how you want to get a wavelength from just 'Ltotal'.
> 
> Even with _only_ conversion from tof, it get much less readable and useful, I think:

I think you are right that it would be less confusing if we also included `tof`. I will try this in a follow-up, where I will fix some handling of inelastic conversions. Those will complicate the graphs, so I will probably split the elastic/inelastic graphs. Then we can maybe include `tof`.

2021-03-05 08:14 UTC, jl-wynen reviewed
Maybe add functions that store results of conversions into datasets, i.e. the equivalent of
```.py
dset.attrs['Ltotal'] = Ltotal(dset)
```
This would prevent potential mistakes from using the wrong name.

2021-03-05 08:14 UTC, jl-wynen commented on neutron/beamline.cpp
>  Variable l1(const dataset::CoordsConstView &meta) {
Uppercase L1 and L2 to match the Python names?

2021-03-05 08:16 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +  if (meta.contains(Dim("Ltotal")))
Unless you are happy with putting this into `scipp` it cannot be `constexpr`, because `Dim(string)` is not.

2021-03-05 08:23 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +  if (meta.contains(Dim("Ltotal")))
... or did you mean a `constexpr char *`, so we'd use `Dim(labels::L2)`?

2021-03-05 08:31 UTC, jl-wynen commented on neutron/beamline.cpp
> +  if (meta.contains(Dim("Ltotal")))
Did not think about this issue. But just the string would work.

2021-03-05 10:30 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +  if (meta.contains(Dim("Ltotal")))
I'll address this in a follow-up I am working on, maybe I can come up with a better mechanism...

2021-03-05 11:45 UTC, merged