Convert dataset slice and other improvements
scipp/scippneutron pull request #30
Opened 2021-03-09 12:40 UTC by SimonHeybrock

- Fixes scipp/scipp#1476
- Fix inifite recursion (kernel crash) when providing unknown dimension label.
- Print known labels in exceptions.

2021-03-10 15:08 UTC, OwenArnold requested changes

2021-03-10 15:08 UTC, OwenArnold commented on neutron/convert.cpp
> +    oss << "Unsupported " << name << " dimension `" << dim
👍  for better error handling.

In addition we need to make these https://github.com/scipp/scippneutron/blob/0d9c7de076fb00ed014cc9c2f1b44c8ea725b9a0/neutron/beamline.cpp#L17-L37 available in the documentation so that users have a fair chance of getting the naming right rather than the trial and error (or look at source code) approach that would currently be required.

Even better (or in addition) we could expose a function to list these `known` dimensions so they can be used programatically.

2021-03-10 15:08 UTC, OwenArnold commented on python/tests/test_mantid.py
>              | sc.is_approx(
You'll need to update this to `isclose`. You can split `rtol` and `atol` as separate args.

2021-03-11 05:55 UTC, SimonHeybrock commented on neutron/convert.cpp
> +    oss << "Unsupported " << name << " dimension `" << dim
They are, see figure here: https://scipp.github.io/scippneutron/user-guide/unit-conversions.html#Beamline-geometry-parameters-used-in-unit-conversions.

2021-03-11 08:06 UTC, OwenArnold approved these changes
Some other `is_approx` usage in tests on the c++ side are failing. Apart from that, looks good.

2021-03-11 08:07 UTC, SimonHeybrock commented
> Some other `is_approx` usage in tests on the c++ side are failing. Apart from that, looks good.

Please have another look, also had to update the Mantid-scipp tests.

2021-03-11 08:09 UTC, OwenArnold commented on python/tests/mantid_scipp_comparison/mantid_scipp_comparison.py
> +                if not sc.all(
Thanks. I'll update this later to use `scipp._util.isnear` as that supersedes this.

2021-03-11 08:11 UTC, OwenArnold approved these changes

2021-03-11 08:12 UTC, SimonHeybrock commented
This is probably going to fail, since I need to update scipp to work around the issue that we cannot have `counts**2` as a unit right now.

2021-03-11 10:37 UTC, merged