Update docs config
scipp/scippneutron pull request #353
Opened 2022-07-20 12:22 UTC by jl-wynen

Only the config itself. These are needed to later build the previous version when making the next but one release.

Based on `scipp-0.15`, so that branch should be merged first.

2022-07-20 13:03 UTC, SimonHeybrock requested changes

2022-07-20 13:03 UTC, SimonHeybrock commented on docs/conf.py
> +    releases = version_info.minor_releases(first='0.8')
This is from scipp, need other min here.

2022-07-20 13:20 UTC, SimonHeybrock commented on .github/workflows/pr_and_main.yml
Erm, you are right 👍

2022-07-21 08:19 UTC, jl-wynen commented
@SimonHeybrock Any more comments?

2022-07-21 08:57 UTC, SimonHeybrock approved these changes

2022-07-21 09:04 UTC, merged