Use sc.dtype.datetime64 for time series logs
scipp/scippneutron pull request #39
Opened 2021-03-16 16:08 UTC by OwenArnold

Fixes https://github.com/scipp/scipp/issues/1698

2021-03-17 08:05 UTC, SimonHeybrock requested changes
Missing changes for `pulse_time`. Should be enough to just remove the current conversion to int we do there.

2021-03-17 08:05 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +                                              unit=sc.units.ns)
If `times` is a numpy array of `datetime`, are the explicit `dtype` and `unit` arguments required?

2021-03-17 08:08 UTC, OwenArnold commented on python/src/scippneutron/mantid.py
> +                                              unit=sc.units.ns)
dtype - no we don't need to have this. possibly makes things clearer but unnecessary otherwise. 
I'm not sure about unit - I'll see if I can remove this.

2021-03-17 09:15 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
>          dims=['event'],
Unrelated, but we could use `sc.empty` instead of `sc.Variable` here and for `coord` to avoid the extra write to memory, for better performance.

2021-03-17 09:16 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
>          dims=['event'],
And we have `sc.ones` now, so we can avoid `sc.broadcast` above?

2021-03-17 09:51 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +                              shape=[n_event]) if load_pulse_times else None
I don't think this is right, this will create with `dtype=double`.

2021-03-18 10:12 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +                      dtype=sc.dtype.float64,
Should be float32 to avoid wasting memory?

2021-03-18 10:19 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> -                      dtype=sc.dtype.float64,
Why? This will be `double`, we want it to be `float32`, as before?

2021-03-18 10:42 UTC, SimonHeybrock approved these changes

2021-03-18 12:03 UTC, merged