MAINT: bump deps and run copier with py3.10
scipp/scippneutron pull request #507
Opened 2024-04-23 14:08 UTC by MridulS

2024-04-23 14:59 UTC, jl-wynen approved these changes

2024-04-25 07:31 UTC, YooSunYoung commented
@scipp/ess-maintainers Here as well. Can someone please update the protection rules?

2024-04-25 08:00 UTC, nvaytet requested changes
The CI didn't run because of an invalid yml file:
```
[Invalid workflow file: .github/workflows/ci.yml#L73](https://github.com/scipp/scippneutron/actions/runs/8802179790/workflow)
The workflow is not valid. In .github/workflows/ci.yml (Line: 73, Col: 11): Error from called workflow scipp/scippneutron/.github/workflows/docs.yml@26b3c1e9abbf1cb751247b743df628ccecc03c47 (Line: 62, Col: 9): Unexpected value 'with'
```

2024-04-25 11:59 UTC, jl-wynen requested changes

2024-04-25 11:59 UTC, jl-wynen commented on .github/workflows/docs.yml
This change does not work. We have to use conda for building the docs because that needs Mantid.

2024-04-25 12:09 UTC, MridulS commented on .github/workflows/docs.yml
Alrighty, need to make sure copier update doesn't mess this up in the future then.

2024-04-29 16:19 UTC, MridulS commented
Trying to run tests with the latest releases and the mantid ones are failing on scipp related ones. Need to investigate this.

2024-05-03 06:58 UTC, jl-wynen approved these changes

2024-05-03 06:59 UTC, jl-wynen commented
@nvaytet Can you check if your comment was addressed? The PR isn't merging because you requested a change.

2024-05-06 08:19 UTC, nvaytet commented on conda/meta.yaml
> +  {% for package in dependencies %}
This is now duplicating the dependencies that are listed above. We should remove the ones above, and only keep `python>=3.10`.

2024-05-06 08:19 UTC, nvaytet commented on docs/conf.py
>  import doctest
Did you check that the rendered docs still look as they should?

2024-05-06 08:19 UTC, nvaytet commented on requirements/base.in
> -scipp[all]
Weird that `scipp[all]` was removed. Should it be there or should it not?

2024-05-06 08:44 UTC, MridulS commented on requirements/base.in
> -scipp[all]
I want to say that yes it should be there? But why none of the actions are tripping up after removing scipp from base requirements 🤔

2024-05-06 08:58 UTC, MridulS commented on requirements/base.in
> -scipp[all]
Well I guess then we shouldn't add the `all` optional identifier. It was added in https://github.com/scipp/scippneutron/pull/471

2024-05-06 09:01 UTC, MridulS commented on docs/conf.py
>  import doctest
I did not. I can not build docs locally as mantid doesn't provide conda packages for arm based Macs.

Looking at the doc build log (which has a green check) it is failing all around inside the doc build! I will look into it :)

2024-05-06 09:12 UTC, nvaytet commented on docs/conf.py
>  import doctest
I usually just download the build docs artifact from the Checks tab, unzip and view locally in a browser

2024-05-06 09:47 UTC, MridulS commented on docs/conf.py
>  import doctest
The artifacts are empty.

2024-05-06 11:13 UTC, nvaytet commented on docs/conf.py
>  import doctest
Weird that this did not fail the build! :thinking: 
The error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 scn.instrument_view(detector.sum('tof'),norm='log')

File ~/work/scippneutron/scippneutron/src/scippneutron/instrument_view.py:277, in instrument_view(scipp_obj, positions, pixel_size, components, **kwargs)
    2[74](https://github.com/scipp/scippneutron/actions/runs/8966725725/job/24623041826#step:7:75)         pixel_size = np.linalg.norm(pos_array[1] - pos_array[0])
    2[76](https://github.com/scipp/scippneutron/actions/runs/8966725725/job/24623041826#step:7:77) fig = pp.scatter3d(scipp_obj, pos=positions, pixel_size=pixel_size, **kwargs)
--> 2[77](https://github.com/scipp/scippneutron/actions/runs/8966725725/job/24623041826#step:7:78) scene = fig.canvas.scene
    279 # Add additional components from the beamline
    280 if components:

AttributeError: 'Box' object has no attribute 'canvas'
```
is because we need to update `plopp` in the `.buildconfig/ci-linux.yml` file to `24.04`

2024-05-06 11:15 UTC, nvaytet commented on .github/workflows/docs.yml
>            find html -type f -name "*.ipynb" -not -path "html/_sources/*" -delete
Are the docs builds not being reported as failing because this line runs after the docs build and succeeds?

2024-05-07 08:00 UTC, MridulS commented on .github/workflows/docs.yml
>            find html -type f -name "*.ipynb" -not -path "html/_sources/*" -delete
I'm not sure, but for now I will create a new issue to track this so this PR isn't blocked. I will fix the issues in the notebooks manually.

2024-05-07 08:02 UTC, MridulS commented on .github/workflows/docs.yml
>            find html -type f -name "*.ipynb" -not -path "html/_sources/*" -delete
Created https://github.com/scipp/scippneutron/issues/510 to track this.

2024-05-15 08:57 UTC, nvaytet approved these changes

2024-05-15 08:57 UTC, merged