Azure pipeline update
scipp/scippneutron pull request #72
Opened 2021-05-04 10:03 UTC by nvaytet

2021-05-13 13:45 UTC, OwenArnold commented on .azure-pipelines/main.yml
> +  - main
Could we also have a pipeline `next` for scippneutron against `scipp/label/dev`? otherwise can do this as a separate PR.

2021-05-14 08:05 UTC, nvaytet commented on .azure-pipelines/main.yml
> +  - main
I would say this would be a nice step to do after this PR so we can test how easy it is to extend this.

2021-05-17 07:05 UTC, OwenArnold requested changes

2021-05-17 07:05 UTC, OwenArnold commented on .azure-pipelines/release.yml
>        - '*.*.*'
Minor point, should we enable `auto_cancel` for this?

2021-05-17 07:05 UTC, OwenArnold commented on conda/bld.bat
> +move %INSTALL_PREFIX%\include\scippneutron* %CONDA_PREFIX%\include\
```suggestion
move %INSTALL_PREFIX%\include\scippneutron %CONDA_PREFIX%\include\
```

2021-05-17 07:05 UTC, OwenArnold commented on conda/bld.bat
> +move %INSTALL_PREFIX%\include\scippneutron* %CONDA_PREFIX%\include\
```suggestion
move %INSTALL_PREFIX%\include\scippneutron-* %CONDA_PREFIX%\include\
```

2021-05-17 07:05 UTC, OwenArnold commented on conda/bld.bat
> +move %INSTALL_PREFIX%\include\scippneutron* %CONDA_PREFIX%\include\
See recent fix made for scipp https://github.com/scipp/scipp/blob/main/conda/bld.bat

2021-05-17 07:05 UTC, OwenArnold commented on conda/meta.yaml
> +  doc_url: https://scipp.github.io/scippneutron
👍

2021-05-17 07:05 UTC, OwenArnold commented on tools/make_and_install.bat
> +cmake --build . --target install --config Release -- /m:%NUMBER_OF_PROCESSORS% || echo ERROR && exit /b
The new `make_and_install.bat` approach (though still wrapped in conda-build) is not documented for scippneutron to my knowledge.

2021-05-17 08:08 UTC, nvaytet commented on .azure-pipelines/release.yml
>        - '*.*.*'
I'm not sure here. We don't have `autoCancel` for either `main` or `release` on both `scipp` and `scippneutron`.
I don't mind either way

2021-05-17 08:45 UTC, OwenArnold commented on .azure-pipelines/release.yml
>        - '*.*.*'
Its maybe too minor to worry about. I think in general you do want `main` to run to completion, but if you realise you made a mistake on release, and you push an updated tag, you probably want to cancel the running one. I think this is too niche a situation to worry about - leave it as is.

2021-05-17 08:46 UTC, OwenArnold commented on conda/build.sh
> +# Using this separate script also minimizes code duplication.
👍

2021-05-17 08:47 UTC, OwenArnold approved these changes

2021-05-17 08:55 UTC, nvaytet commented
do not merge yet, I still need to make a test run with py3.8

2021-05-18 08:14 UTC, nvaytet commented
Ok, there are too many conda conflicts to create a py3.8 scippneutron, so for now, we will only release 3.7.
We can come back to this later if we want to add the 3.8.

2021-05-18 08:51 UTC, merged