scippneutron with scipp>0.6.1 (shallow copy changes)
scipp/scippneutron pull request #73
Opened 2021-05-04 11:06 UTC by OwenArnold

2021-05-05 04:03 UTC, SimonHeybrock reviewed
I know this is a draft, but had a short (partial) look anyway:

2021-05-05 04:03 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +    data_and_geom_match = spec_dim == 'spectrum'
How does this occur? Aren't Mantid workspaces always 2D? With geometry info related to the second axis?

2021-05-06 13:06 UTC, OwenArnold commented on neutron/convert.cpp
> +#include <sstream>
No `sstream` must be included for `std::ostringstream`

2021-05-06 13:35 UTC, OwenArnold commented on docs/tutorials/powder-diffraction.ipynb
> +    "dspacing_vanadium = scn.convert(vanadium.copy(), 'tof', 'dspacing', scatter=True)\n",
Note the copy here is a work-around for an existing bug rather than a desirable fix. What's happening here is that `convert` will acted upon the coords of the data (bins) of the input, so `sample.data.coords` becomes `dspacing`. This causes a failure further down in the script where a convert for `sample` from `tof` to `wavelength` is attempted, this has no effect and the coord remains in `dspacing` - I believe this could be a fundamental problem with the copy constructor behaviour for `DataArray` but will investigate separately.

2021-05-07 04:32 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +    data_and_geom_match = spec_dim == 'spectrum'
We should not be adding something with `spectrum` dimension in that case. If the spectrum-axis has dimension Q then so should the geometry information. Mantid has a 1:1 correspondence between axis and these meta data, so that should be preserved. What is the problem with having say the `position` coord depend on the spectrum-axis?

2021-05-07 04:35 UTC, SimonHeybrock commented on docs/tutorials/powder-diffraction.ipynb
> +    "dspacing_vanadium = scn.convert(vanadium.copy(), 'tof', 'dspacing', scatter=True)\n",
Maybe you can explain in a call. (shallow) copying a data arrays makes copies of the meta-data dicts so there should not be a problem here.

2021-05-07 04:37 UTC, SimonHeybrock commented on neutron/convert.cpp
> +#include <sstream>
Then that should replace the `ostream` include above?

2021-05-07 04:42 UTC, SimonHeybrock commented on python/tests/test_neutron.py
> -
Given that we are considering to add this again later, have you considered not removing it (which would break existing notebooks), but rather accept the out arg and simply assign to it?

2021-05-18 05:41 UTC, SimonHeybrock requested changes
Had a look at the more recent changes, I think this is almost done? See comments below.

There are also a couple outstanding comments above I believe.

2021-05-18 05:41 UTC, SimonHeybrock commented on neutron/beamline.cpp
>      return copy(meta[NeutronDim::Ltotal]);
Remove `copy` and `TODO`

2021-05-18 05:41 UTC, SimonHeybrock commented on neutron/beamline.cpp
> +  return var / norm(var);
I think you renamed already, remove TODO?

2021-05-18 05:41 UTC, SimonHeybrock commented on neutron/convert.cpp
> +  return out[d.name()];
Why do we need to do this via dataset now? It also has the effect of marking the attributes readonly, which should not be required here?

2021-05-18 05:41 UTC, SimonHeybrock commented on python/src/scippneutron/mantid.py
> +    if not ws.id() == 'MaskWorkspace':
Can you elaborate? Why this change? What is this doing?

2021-05-18 12:32 UTC, OwenArnold commented on python/src/scippneutron/mantid.py
> +    if not ws.id() == 'MaskWorkspace':
This information is fictional for a mask workspace. Attempts to add an empty dimension variable (length 1) with value (1). The fact that the mask workspace carries this at all more speaks for the fixed nature of the MatrixWorkspace.

2021-05-24 08:42 UTC, SimonHeybrock commented on neutron/convert.cpp
> +    d.rename(from, to);
Hmmm, not quite? `rename` is also renaming the dimension, which we might not want to skip, even if there is no such coord?

2021-05-24 08:51 UTC, SimonHeybrock commented on neutron/convert.cpp
> +                                 NeutronDim::SourcePosition};
Should the positions (and actually also the `L*` coords) be included in the subspan below?

2021-05-24 08:55 UTC, SimonHeybrock commented on neutron/test/convert_test.cpp
> +  ASSERT_FALSE(energy.coords().contains(NeutronDim::SamplePosition));
I suppose this would be fixed by my comment above on the `pos_invariant` subspan.

2021-05-24 10:14 UTC, SimonHeybrock commented on neutron/convert.cpp
> +#include <sstream>
Do we need `sstream` AND `ostream`?

2021-05-25 04:45 UTC, SimonHeybrock commented on .azure-pipelines/main.yml
> +# New releases of scipp will automatically cause this pipeline to run
Is the idea here that this would publish an updated package, provided that there are no breaking changes?

What if it fails? Would conda install the wrong (new) upstream scipp but the old scippneutron, leading to failures when running? Would this not that imply that we should therefore require a specific version (maximum) version in scippneutron (maybe allowing different patch releases)?

2021-05-25 04:46 UTC, SimonHeybrock commented on .azure-pipelines/next.yml
> +# New releases of scipp will automatically cause this pipeline to run
Can you explain? I thought the idea of `next` was to use the `Main` builds of scipp?

2021-05-25 04:50 UTC, SimonHeybrock commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
I don't think this true? We *do* want to have CI just as usual when merging `next` into `main`. Where we need the `next` pipelines is for PRs *into* `next`.

2021-05-26 12:48 UTC, OwenArnold commented on .azure-pipelines/main.yml
> +# New releases of scipp will automatically cause this pipeline to run
At present this will only run when the `scipp` `Release pipleline` fully completes. That requires a tagged version of scipp.

A new `scippneutron` would only be made available if the pipeline fully completes. We probably need to do this manually or otherwise because new releases of `scipp/label/main` have the potential to break `scipp/label/dev::scippneutron`.

Another potentially better way of handling our requirements for a safe release procedure would be to somehow put scippneutron as a stage in the scipp release pipeline. The same would be true of scippneutron->ess.

2021-05-26 12:50 UTC, OwenArnold commented on .azure-pipelines/next.yml
> +# New releases of scipp will automatically cause this pipeline to run
Well `scipp/label/dev::scippneutron` uses `scipp/label/main::scipp`. This is specifically for working against the next planned release of scipp, i.e. using `scipp/label/main::scipp`

2021-05-26 12:52 UTC, OwenArnold commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
Yes indeed. The changes here are just to prevent wasteful (almost guranteed breaking) runs of next scippneutron against `scipp/label/main::scipp`.

Basically we need another pipeline file to do as you say.

2021-05-26 12:53 UTC, SimonHeybrock commented on .azure-pipelines/next.yml
> +# New releases of scipp will automatically cause this pipeline to run
So be "releases" you don't mean releases but dev releases?

2021-05-26 12:53 UTC, OwenArnold commented on neutron/convert.cpp
> +#include <sstream>
No, I will change.

2021-05-26 12:54 UTC, OwenArnold commented on neutron/convert.cpp
> +                                 NeutronDim::SourcePosition};
We should talk about this on a separate call. There are some things around the testing that you've highlighted that I need to discuss/resolve too.

2021-05-26 12:56 UTC, OwenArnold commented on neutron/convert.cpp
> +  return out[d.name()];
Yes, if i recall the problem is this https://github.com/scipp/scippneutron/blob/next/neutron/convert.cpp#L37, so we need to find a better way to work around this.

2021-05-26 12:56 UTC, SimonHeybrock commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
Didn't you add that file above?

I really don't think this should be disabled. If we merge `next` into `main` we want PR builds to run. What should be done instead is to *not* work directly on `next`. Treat `next` as if it was `main`, i.e., create PRs into `next`. PRs into `next` should use the `Next` pipeline.

If we just don't open the PR `next -> main` too early we don't run into the problems you are seeing now, I think.

2021-05-26 12:57 UTC, OwenArnold commented on .azure-pipelines/next.yml
> +# New releases of scipp will automatically cause this pipeline to run
Yes, will fix working.

2021-05-26 12:57 UTC, SimonHeybrock commented on neutron/convert.cpp
> +  return out[d.name()];
Define `iter()`?

2021-05-26 13:02 UTC, OwenArnold commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
I think what we want to say is that for this particular pipeline, we only want to consider prs where `main` in the base/target branch. In this case, yes we should drop the `exclude` of `next`. I think we can do this in azure, I'll have to remind myself how.

We would then have a similar pipeline with some different channel settings for prs where `next` is the base/target branch

2021-05-26 13:05 UTC, SimonHeybrock commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
Can you just conditionally select the conda channel based on the base branch, but use the same pipeline?

2021-05-26 13:11 UTC, OwenArnold commented on .azure-pipelines/pull_request.yml
> +      - next # Next has dedicated pipeline and is by nature incompatible with the stable scipp
> Can you just conditionally select the conda channel based on the base branch, but use the same pipeline?

Yes that should be doable.

2021-06-01 09:26 UTC, nvaytet commented
@OwenArnold you seem to have committed the outputs in the `exploring_data` notebook...

2021-06-01 09:42 UTC, nvaytet commented on docs/tutorials/working-with-masks.ipynb
> +    "- Define `x = data.coords['position'].x1` to extract only the x-component of the position coordinate.\n",
This will now change again with the `fields.x` properties

2021-06-01 09:42 UTC, nvaytet commented on neutron/convert.cpp
> +                                  : scipp::span(params).subspan(8);
Can you explain why this change was needed?

2021-06-01 09:42 UTC, nvaytet commented on scippneutron-developer-no-mantid.yml
> +  - traitlets=4.3.3 # see https://github.com/jupyter-widgets/pythreejs/issues/334
I believe this pinning and the one below on `sphinx` are no longer needed.

2021-06-01 09:42 UTC, nvaytet commented on scippneutron-developer.yml
> +  - ipython=7.2.0
i don't think this is needed anymore

2021-06-01 11:13 UTC, SimonHeybrock commented on neutron/convert.cpp
> +  auto convert_item = [&](auto &item) {
Why is the loop body extracted as a lambda now?

2021-06-01 11:16 UTC, SimonHeybrock commented on neutron/convert.cpp
> +  if (it != keys.end())
Why not `if(d.dims().contains(from))`?

2021-06-01 11:24 UTC, SimonHeybrock commented on neutron/convert.cpp
> +                                  : scipp::span(params).subspan(8);
This can best be understood looking at the graph in https://scipp.github.io/scippneutron/user-guide/unit-conversions.html#Beamline-geometry-parameters-used-in-unit-conversions. We have some "intermediate" conversions where some position information is still relevant (`wavelength`, for example), and other such as `dspacing` that are position-invariant.

2021-06-01 11:26 UTC, SimonHeybrock commented on neutron/convert.cpp
>    }
Probably shorter and more obvious than adding the `IteratorFacade`:
```cpp
if constexpr (std::is_same_v<T, DataArray>)
  convert_item(d);
else
  for (auto &&item : d)
    convert_item(item);
```

2021-06-01 12:14 UTC, OwenArnold commented on neutron/convert.cpp
> +  if (it != keys.end())
Yes, contains better. Forgot we had that.

2021-06-01 12:15 UTC, OwenArnold commented on neutron/convert.cpp
>    }
There are a number of usages of `iter` within `convert.cpp`. I did originally have something similar to what you have above, but quickly ended up looking messy/duplicated.

2021-06-01 12:49 UTC, SimonHeybrock commented
@OwenArnold @nvaytet Have a look at my commits, I think it addresses Neil's as well as my comments. Also deduplicated the convert details between dense coords and event coords.

2021-06-01 12:59 UTC, SimonHeybrock commented on conda/meta.yaml
> +    - boost {{ boost }}
@OwenArnold Why this?

2021-06-01 13:00 UTC, SimonHeybrock commented on docs/tutorials/exploring-data.ipynb
> +    "data = scn.load(filename='/Users/spu92482/Downloads/LARMOR00049338.nxs')"
@OwenArnold Was this committed by accident?

2021-06-01 13:04 UTC, SimonHeybrock commented on neutron/convert.cpp
>        }
@OwenArnold It seems this comment was not addressed, in fact it looks like in the current version we are not setting attrs as readonly any more?

2021-06-01 13:28 UTC, OwenArnold commented on conda/meta.yaml
> +    - boost {{ boost }}
I recall that we had other cases where the `mantid-framework` boost runtime version was being stamped on. But I don't 100% recall it might have been from debugging. Please try to remove.

2021-06-01 13:49 UTC, nvaytet approved these changes
Apart from the current parsing issues in the CI, looks good to me

2021-06-03 07:42 UTC, merged