Mantid deployment docs
scipp/scippneutron pull request #78
Opened 2021-05-17 12:26 UTC by OwenArnold

Moved across from scipp and corrected

We should merge this after Neil has made changes to the mantid-framework recipe

2021-05-18 12:25 UTC, nvaytet requested changes

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +Successful pipline execution pushes new packages to `Anaconda Cloud <https://anaconda.org/scipp/mantid-framework>`_.
```suggestion
Successful pipeline execution pushes new packages to `Anaconda Cloud <https://anaconda.org/scipp/mantid-framework>`_.
```

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +Our second pipleline uses latest ``master`` of mantid to produce (but not publish) a nightly package, against our static recipie.
```suggestion
Our second pipeline uses the latest ``master`` from mantid to produce (but not publish) a nightly package, against our static recipe.
```

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +#. Check the nightly build pipeline on azure and verify successful completion.
Add link to the pipeline in question here? as we have talked about many pipelines above, it may no longer be clear (even though you do say above which one it should be)

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +Our third pipeline is triggered by github pull requests only. This is used to produce (but no publish) packages given changes in our recipe, but against the same mantid SHA1 as is used for the tagged
split long lines

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +  As part of the ``conda build`` step mantid's imports are tested. Packaging can therefore fail if mantid does not appear to work (import).
```suggestion
  Mantid's imports are tested as part of the ``conda build`` step. Packaging can therefore fail if mantid does not appear to work (import).
```

2021-05-18 12:25 UTC, nvaytet commented on docs/developer/deployment.rst
> +  When running ``conda build`` locally, ensure that ``conda-build`` is up to date (``conda update conda-build``). This can be a source of difference between what is observed on the CI (install fresh
Split long lines

2021-05-18 12:53 UTC, OwenArnold commented on docs/developer/deployment.rst
> +#. Check the nightly build pipeline on azure and verify successful completion.
I did think about that, but was concerned that a renaming of the pipeline would make the docs-azure links too fragile.

2021-05-26 10:00 UTC, nvaytet approved these changes

2021-06-04 10:33 UTC, nvaytet commented
@OwenArnold is this ready to be merged?

2021-06-04 13:08 UTC, merged